import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes';
import userRoutes from '../modules/user/user.routes';
import patientRoutes from '../modules/patient/patient.routes';
import ashaRoutes from '../modules/asha/asha.routes';
import hospitalRoutes from '../modules/hospital/hospital.routes';
import facilityRoutes from '../modules/facility/facility.routes';
import departmentRoutes from '../modules/department/department.routes';
import doctorRoutes from '../modules/doctor/doctor.routes';
import rosterRoutes from '../modules/doctor/roster.routes';
import queueRoutes from '../modules/queue/queue.routes';
import tokenRoutes from '../modules/token/token.routes';
import appointmentRoutes from '../modules/appointment/appointment.routes';
import encounterRoutes from '../modules/encounter/encounter.routes';
import referralRoutes from '../modules/referral/referral.routes';
import teleconsultationRoutes from '../modules/teleconsultation/teleconsultation.routes';
import ehrRoutes from '../modules/ehr/ehr.routes';
import consentRoutes from '../modules/consent/consent.routes';
import medicineRoutes from '../modules/medicine/medicine.routes';
import bloodRoutes from '../modules/blood/blood.routes';
import bedRoutes from '../modules/bed/bed.routes';
import ambulanceRoutes from '../modules/ambulance/ambulance.routes';
import equipmentRoutes from '../modules/equipment/equipment.routes';
import followupRoutes from '../modules/followup/followup.routes';
import notificationRoutes from '../modules/notification/notification.routes';
import syncRoutes from '../modules/sync/sync.routes';
import searchRoutes from '../modules/search/search.routes';
import analyticsRoutes from '../modules/analytics/analytics.routes';
import aiRoutes from '../modules/ai/ai.routes';
import auditRoutes from '../modules/audit/audit.routes';
import prescriptionRoutes from '../modules/encounter/prescription.routes';
import diagnosticRoutes from '../modules/encounter/diagnostic.routes';
import superAdminRoutes from '../modules/superadmin/superadmin.routes';
import adminRoutes from '../modules/admin/admin.routes';
import operationsRoutes from '../modules/operations/operations.routes';
import clerkRoutes from '../modules/clerk/clerk.routes';
import pharmacyRoutes from '../modules/pharmacy/pharmacy.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/patients', patientRoutes);
router.use('/asha', ashaRoutes);
router.use('/hospitals', hospitalRoutes);
router.use('/facilities', facilityRoutes);
router.use('/departments', departmentRoutes);
router.use('/specialties', departmentRoutes);
router.use('/doctors', doctorRoutes);
router.use('/rosters', rosterRoutes);
router.use('/queues', queueRoutes);
router.use('/tokens', tokenRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/encounters', encounterRoutes);
router.use('/prescriptions', prescriptionRoutes);
router.use('/diagnostics', diagnosticRoutes);
router.use('/referrals', referralRoutes);
router.use('/teleconsultations', teleconsultationRoutes);
router.use('/consents', consentRoutes);
router.use('/medicines', medicineRoutes);
router.use('/blood', bloodRoutes);
router.use('/emergency', bloodRoutes);
router.use('/beds', bedRoutes);
router.use('/ambulances', ambulanceRoutes);
router.use('/equipment', equipmentRoutes);
router.use('/followups', followupRoutes);
router.use('/notifications', notificationRoutes);
router.use('/sync', syncRoutes);
router.use('/search', searchRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/ai', aiRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/super-admin', superAdminRoutes);
router.use('/admin', adminRoutes);
router.use('/operations', operationsRoutes);
router.use('/clerk', clerkRoutes);
router.use('/pharmacy', pharmacyRoutes);

// Register Longitudinal EHR & Break-Glass direct routes
router.use('/', ehrRoutes);

export default router;
