import { FacilityModel } from '../models/Facility';
import { DoctorModel } from '../models/Doctor';
import { UserModel } from '../models/User';
import { RoleModel } from '../models/Role';
import { PatientModel } from '../models/Patient';
import { MedicineModel } from '../models/Medicine';
import { BloodCenterModel } from '../models/BloodCenter';
import { MedicalStoreModel } from '../models/MedicalStore';

export const SEED_ROLES = [
  {
    id: 'role_super_admin',
    code: 'SUPER_ADMIN',
    name: 'State Apex Super Administrator',
    description: 'Full state-wide administrative authority across all districts, hospitals, technical AI models, system health, and cross-district user governance.',
    level: 'STATE',
    permissions: [
      'system:manage:all',
      'district:manage:all',
      'facility:manage:all',
      'user:manage:all',
      'role:manage:all',
      'ai_models:deploy',
      'ai_models:rollback',
      'audit:read:all',
      'analytics:read:state',
      'queue:override:state',
    ],
    isSystem: true,
    isActive: true,
  },
  {
    id: 'role_district_admin',
    code: 'DISTRICT_ADMIN',
    name: 'District Chief Medical Administrator (CDHO)',
    description: 'District command authority for facility oversight, hospital staff provisioning, ambulance tracking, epidemic intelligence, and resource allocation within assigned district.',
    level: 'DISTRICT',
    permissions: [
      'district:manage:own',
      'facility:manage:district',
      'user:manage:district',
      'staff:provision:district',
      'referral:coordinate',
      'ambulance:dispatch:district',
      'epidemic:track:district',
      'inventory:reallocate:district',
      'analytics:read:district',
    ],
    isSystem: true,
    isActive: true,
  },
  {
    id: 'role_hospital_admin',
    code: 'HOSPITAL_ADMIN',
    name: 'Hospital Superintendent & Operations Admin',
    description: 'Hospital-level operational control for bed allocation, OPD department configuration, on-duty specialist rostering, and hospital staff management.',
    level: 'FACILITY',
    permissions: [
      'facility:manage:own',
      'opd:configure:facility',
      'doctor:roster:facility',
      'beds:allocate:facility',
      'staff:manage:facility',
      'queue:manage:facility',
      'inventory:manage:facility',
    ],
    isSystem: true,
    isActive: true,
  },
  {
    id: 'role_doctor',
    code: 'DOCTOR',
    name: 'Medical Officer & Specialist Physician',
    description: 'Clinical examination, live queue consultation, digital Rx prescription generation, lab investigations, e-referrals, and teleconsultation.',
    level: 'FACILITY',
    permissions: [
      'queue:call_patient',
      'consultation:write',
      'prescription:issue',
      'lab:order',
      'referral:create',
      'teleconsult:attend',
      'emr:read_write',
    ],
    isSystem: true,
    isActive: true,
  },
  {
    id: 'role_facility_staff',
    code: 'FACILITY_STAFF',
    name: 'Hospital Auxiliary Staff & Technicians',
    description: 'Hospital operations including OPD registration clerk, pharmacy dispensing, pathology laboratory testing, and triage nursing.',
    level: 'FACILITY',
    permissions: [
      'token:generate',
      'patient:register',
      'pharmacy:dispense',
      'lab:upload_result',
      'vital_signs:record',
    ],
    isSystem: true,
    isActive: true,
  },
  {
    id: 'role_asha',
    code: 'ASHA',
    name: 'ASHA & Community Health Worker',
    description: 'Grassroots community health surveillance, home health surveys, ANC/immunization tracking, emergency triage, and telehealth facilitation.',
    level: 'COMMUNITY',
    permissions: [
      'community:survey',
      'anc:track',
      'immunization:log',
      'telehealth:request',
      'emergency:flag',
    ],
    isSystem: true,
    isActive: true,
  },
  {
    id: 'role_patient',
    code: 'PATIENT',
    name: 'Citizen & Registered Patient',
    description: 'Public patient portal access for appointment scheduling, live token tracking, AI symptom triage, ABHA health locker, and medicine orders.',
    level: 'CITIZEN',
    permissions: [
      'appointment:book',
      'token:request',
      'ai_chat:use',
      'records:view_own',
      'prescription:download',
    ],
    isSystem: true,
    isActive: true,
  },
];

export const SEED_FACILITIES = [
  // Gandhinagar
  {
    id: 'fac_civil_01',
    name: 'Gandhinagar Civil Hospital & Medical College',
    type: 'DISTRICT_HOSPITAL',
    district: 'Gandhinagar',
    state: 'Gujarat',
    address: 'Sector 12, Gandhinagar, Gujarat 382012',
    pincode: '382012',
    contactNumber: '079-2322-1916',
    emergencyNumber: '108',
    coordinates: { lat: 23.2156, lng: 72.6369 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 15,
    totalBeds: 650,
    availableBeds: 84,
    icuBedsTotal: 60,
    icuBedsAvailable: 12,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: [
      'General Medicine',
      'Cardiology',
      'Orthopedics',
      'Pediatrics',
      'Obstetrics & Gynecology',
      'General Surgery',
      'Dermatology',
      'Ophthalmology',
      'ENT',
      'Neurology',
    ],
    departments: [
      { id: 'dep_med', name: 'General Medicine OPD', code: 'GM-OPD', activeDoctors: 4, currentWaitMinutes: 12, opdOpen: true },
      { id: 'dep_cardio', name: 'Cardiology OPD', code: 'CARD-OPD', activeDoctors: 2, currentWaitMinutes: 20, opdOpen: true },
      { id: 'dep_ortho', name: 'Orthopedics OPD', code: 'ORTHO-OPD', activeDoctors: 3, currentWaitMinutes: 15, opdOpen: true },
      { id: 'dep_pedia', name: 'Pediatrics OPD', code: 'PED-OPD', activeDoctors: 2, currentWaitMinutes: 10, opdOpen: true },
      { id: 'dep_obg', name: 'Obstetrics & Gynecology OPD', code: 'OBG-OPD', activeDoctors: 3, currentWaitMinutes: 18, opdOpen: true },
    ],
  },
  // Rajkot
  {
    id: 'fac_raj_civil_01',
    name: 'PDU Government Medical College & Civil Hospital',
    type: 'DISTRICT_HOSPITAL',
    district: 'Rajkot',
    state: 'Gujarat',
    address: 'Hospital Chowk, Rajkot, Gujarat 360001',
    pincode: '360001',
    contactNumber: '0281-2458331',
    emergencyNumber: '108',
    coordinates: { lat: 22.3039, lng: 70.8022 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 12,
    totalBeds: 850,
    availableBeds: 110,
    icuBedsTotal: 75,
    icuBedsAvailable: 18,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: ['General Medicine', 'Cardiology', 'Orthopedics', 'General Surgery', 'Pediatrics', 'Obstetrics & Gynecology'],
    departments: [
      { id: 'dep_raj_med', name: 'General Medicine OPD', code: 'RJK-GM', activeDoctors: 5, currentWaitMinutes: 10, opdOpen: true },
      { id: 'dep_raj_surg', name: 'General Surgery OPD', code: 'RJK-SURG', activeDoctors: 3, currentWaitMinutes: 15, opdOpen: true },
    ],
  },
  {
    id: 'fac_raj_gondal_02',
    name: 'Gondal Sub-District Hospital',
    type: 'SUB_DISTRICT_HOSPITAL',
    district: 'Rajkot',
    state: 'Gujarat',
    address: 'Gondal Bypass, Rajkot, Gujarat 360311',
    pincode: '360311',
    contactNumber: '02825-220145',
    emergencyNumber: '108',
    coordinates: { lat: 21.9619, lng: 70.7997 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 10,
    totalBeds: 120,
    availableBeds: 24,
    icuBedsTotal: 10,
    icuBedsAvailable: 3,
    oxygenAvailable: true,
    bloodBankAvailable: false,
    ambulanceAvailable: true,
    specialties: ['General Medicine', 'Pediatrics', 'Maternal Health'],
    departments: [
      { id: 'dep_gondal_med', name: 'General OPD', code: 'GNDL-OPD', activeDoctors: 2, currentWaitMinutes: 10, opdOpen: true },
    ],
  },
  // Ahmedabad
  {
    id: 'fac_un_mehta',
    name: 'U. N. Mehta Institute of Cardiology & Research Centre',
    type: 'SPECIALTY_HOSPITAL',
    district: 'Ahmedabad',
    state: 'Gujarat',
    address: 'Civil Hospital Campus, Asarwa, Ahmedabad 380016',
    pincode: '380016',
    contactNumber: '079-2268-4200',
    emergencyNumber: '108',
    coordinates: { lat: 23.0524, lng: 72.5932 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 10,
    totalBeds: 1251,
    availableBeds: 142,
    icuBedsTotal: 180,
    icuBedsAvailable: 34,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: ['Cardiology', 'Cardiac Surgery', 'Interventional Cardiology', 'Pediatric Cardiology', 'Cath Lab', 'Emergency CCU'],
    departments: [
      { id: 'dep_cardio_apex', name: '24x7 Cath Lab & Emergency Cardiology', code: 'CARD-APEX', activeDoctors: 6, currentWaitMinutes: 10, opdOpen: true },
    ],
  },
  {
    id: 'fac_ikdrc',
    name: 'Institute of Kidney Diseases and Research Centre (IKDRC)',
    type: 'SPECIALTY_HOSPITAL',
    district: 'Ahmedabad',
    state: 'Gujarat',
    address: 'Civil Hospital Campus, Asarwa, Ahmedabad 380016',
    pincode: '380016',
    contactNumber: '079-2268-7000',
    emergencyNumber: '108',
    coordinates: { lat: 23.0538, lng: 72.5945 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 15,
    totalBeds: 450,
    availableBeds: 58,
    icuBedsTotal: 50,
    icuBedsAvailable: 14,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: ['Nephrology', 'Urology', 'Dialysis', 'Kidney Transplant', 'Renal Medicine'],
    departments: [
      { id: 'dep_nephro', name: 'Nephrology & Hemodialysis Unit', code: 'NEPH-OPD', activeDoctors: 4, currentWaitMinutes: 12, opdOpen: true },
    ],
  },
  {
    id: 'fac_gcri',
    name: 'The Gujarat Cancer & Research Institute (GCRI)',
    type: 'SPECIALTY_HOSPITAL',
    district: 'Ahmedabad',
    state: 'Gujarat',
    address: 'M. P. Shah Cancer Hospital, Civil Hospital Campus, Asarwa, Ahmedabad 380016',
    pincode: '380016',
    contactNumber: '079-2268-8000',
    emergencyNumber: '108',
    coordinates: { lat: 23.0545, lng: 72.5928 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 20,
    totalBeds: 650,
    availableBeds: 72,
    icuBedsTotal: 40,
    icuBedsAvailable: 9,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: ['Oncology', 'Medical Oncology', 'Surgical Oncology', 'Radiation Oncology', 'Chemotherapy Daycare'],
    departments: [
      { id: 'dep_med_onc', name: 'Medical Oncology & Chemotherapy', code: 'ONC-MED', activeDoctors: 5, currentWaitMinutes: 15, opdOpen: true },
    ],
  },
  // Surat
  {
    id: 'fac_surat_civil_01',
    name: 'New Civil Hospital Surat (Govt Medical College)',
    type: 'DISTRICT_HOSPITAL',
    district: 'Surat',
    state: 'Gujarat',
    address: 'Majura Gate, Surat, Gujarat 395001',
    pincode: '395001',
    contactNumber: '0261-2244175',
    emergencyNumber: '108',
    coordinates: { lat: 21.1702, lng: 72.8311 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 14,
    totalBeds: 780,
    availableBeds: 110,
    icuBedsTotal: 65,
    icuBedsAvailable: 15,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: ['General Medicine', 'General Surgery', 'Pediatrics', 'Obstetrics & Gynecology'],
    departments: [
      { id: 'dep_surat_gm', name: 'General Medicine OPD', code: 'SRT-GM', activeDoctors: 4, currentWaitMinutes: 12, opdOpen: true },
    ],
  },
  // Vadodara
  {
    id: 'fac_vad_ssg_01',
    name: 'Sir Sayajirao General (SSG) Hospital',
    type: 'DISTRICT_HOSPITAL',
    district: 'Vadodara',
    state: 'Gujarat',
    address: 'Jail Road, Sayajigunj, Vadodara, Gujarat 390001',
    pincode: '390001',
    contactNumber: '0265-2424848',
    emergencyNumber: '108',
    coordinates: { lat: 22.3107, lng: 73.1812 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 12,
    totalBeds: 900,
    availableBeds: 92,
    icuBedsTotal: 70,
    icuBedsAvailable: 16,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: ['General Medicine', 'Orthopedics', 'Cardiology', 'Pediatrics'],
    departments: [
      { id: 'dep_ssg_gm', name: 'General Medicine OPD', code: 'SSG-GM', activeDoctors: 5, currentWaitMinutes: 10, opdOpen: true },
    ],
  },
];

export const SEED_DOCTORS = [
  {
    id: 'doc_patel_01',
    name: 'Dr. Arvind Patel',
    qualification: 'MBBS, MD (General Medicine)',
    specialty: 'General Medicine',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    departmentId: 'dep_med',
    departmentName: 'General Medicine OPD',
    roomNumber: 'Room 4 (1st Floor)',
    status: 'AVAILABLE',
    activeTokenId: null,
    queueLength: 0,
    patientsToday: 12,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-18492',
  },
  {
    id: 'doc_raj_01',
    name: 'Dr. Hardik Vora',
    qualification: 'MBBS, MS (General Surgery)',
    specialty: 'General Surgery',
    facilityId: 'fac_raj_civil_01',
    facilityName: 'PDU Government Medical College & Civil Hospital',
    departmentId: 'dep_raj_surg',
    departmentName: 'General Surgery OPD',
    roomNumber: 'Room 102 (Ground Floor)',
    status: 'AVAILABLE',
    activeTokenId: null,
    queueLength: 0,
    patientsToday: 8,
    teleconsultEnabled: true,
    district: 'Rajkot',
    registrationNumber: 'G-24819',
  },
  {
    id: 'doc_cardio_01',
    name: 'Dr. K. P. Trivedi',
    qualification: 'MBBS, MD, DM (Cardiology)',
    specialty: 'Cardiology',
    facilityId: 'fac_un_mehta',
    facilityName: 'U. N. Mehta Institute of Cardiology & Research Centre',
    departmentId: 'dep_cardio_apex',
    departmentName: '24x7 Cath Lab & Emergency Cardiology',
    roomNumber: 'Cath Lab Suite 1',
    status: 'AVAILABLE',
    activeTokenId: null,
    queueLength: 0,
    patientsToday: 15,
    teleconsultEnabled: true,
    district: 'Ahmedabad',
    registrationNumber: 'G-31902',
  },
];

export async function seedInitialDatabase(): Promise<void> {
  try {
    // 1. Seed Facilities
    const facCount = await FacilityModel.countDocuments();
    if (facCount === 0) {
      console.log('[Seed] Seeding initial healthcare facilities...');
      await FacilityModel.insertMany(SEED_FACILITIES);
    }

    // 2. Seed Doctors
    const docCount = await DoctorModel.countDocuments();
    if (docCount === 0) {
      console.log('[Seed] Seeding initial hospital doctors...');
      await DoctorModel.insertMany(SEED_DOCTORS);
    }

    // 3. Seed Canonical Roles in RoleModel
    for (const r of SEED_ROLES) {
      await RoleModel.findOneAndUpdate(
        { code: r.code },
        { $set: r },
        { upsert: true, new: true }
      );
    }

    // 4. Seed Canonical Users for Clean Authentication & Role Access
    const CANONICAL_USERS = [
      // District Admin (Rajkot - Meet Pipaliya)
      {
        id: 'usr_dist_raj',
        name: 'Meet Pipaliya',
        username: 'meet',
        email: 'meet@gmail.com',
        phone: '9876500026',
        password: 'password',
        role: 'DISTRICT_ADMIN',
        district: 'Rajkot',
        designation: 'Chief District Health Officer (CDHO)',
        status: 'ACTIVE',
      },
      // Super Admin (State Apex Grid)
      {
        id: 'usr_super_01',
        name: 'Dr. Jayesh Trivedi',
        username: 'superadmin',
        email: 'superadmin@gujarat.health.gov.in',
        phone: '9876500001',
        password: 'password123',
        role: 'SUPER_ADMIN',
        district: 'Gandhinagar',
        designation: 'State Principal Health Secretary',
        status: 'ACTIVE',
      },
      // District Admin (Gandhinagar)
      {
        id: 'usr_dist_01',
        name: 'Dr. Bhavik Mehta',
        username: 'districtadmin',
        email: 'bhavik.cdho@gandhinagar.health.gov.in',
        phone: '9876500006',
        password: 'password123',
        role: 'DISTRICT_ADMIN',
        district: 'Gandhinagar',
        designation: 'Chief District Health Officer (CDHO)',
        status: 'ACTIVE',
      },
      // Doctor on Duty
      {
        id: 'usr_doc_01',
        name: 'Dr. Arvind Patel',
        username: 'doctor',
        email: 'dr.arvind.patel@gujarat.gov.in',
        phone: '9876500002',
        password: 'password123',
        role: 'DOCTOR',
        facilityId: 'fac_civil_01',
        facilityName: 'Gandhinagar Civil Hospital & Medical College',
        district: 'Gandhinagar',
        specialty: 'General Medicine',
        department: 'General Medicine OPD',
        designation: 'Chief Medical Officer (OPD)',
        status: 'ACTIVE',
      },
      // Facility Staff (Pharmacist)
      {
        id: 'usr_pharm_01',
        name: 'Vikram Joshi',
        username: 'pharmacist',
        email: 'vikram.pharm@gujarat.gov.in',
        phone: '9876500003',
        password: 'password123',
        role: 'FACILITY_STAFF',
        staffSubType: 'PHARMACIST',
        facilityId: 'fac_civil_01',
        facilityName: 'Gandhinagar Civil Hospital & Medical College',
        district: 'Gandhinagar',
        designation: 'Chief Pharmacist (Central Dispensary)',
        status: 'ACTIVE',
      },
      // Facility Staff (Registration Clerk)
      {
        id: 'usr_clerk_01',
        name: 'Govind Parmar',
        username: 'staff',
        email: 'govind.clerk@gujarat.gov.in',
        phone: '9876500004',
        password: 'password123',
        role: 'FACILITY_STAFF',
        staffSubType: 'REGISTRATION_CLERK',
        facilityId: 'fac_civil_01',
        facilityName: 'Gandhinagar Civil Hospital & Medical College',
        district: 'Gandhinagar',
        designation: 'Senior Registration Counter Officer',
        status: 'ACTIVE',
      },
      // ASHA Worker
      {
        id: 'usr_asha_01',
        name: 'Anitaben Patel',
        username: 'asha',
        email: 'anita.asha@gujarat.gov.in',
        phone: '9876500009',
        password: 'password123',
        role: 'ASHA',
        facilityId: 'fac_civil_01',
        facilityName: 'Gandhinagar Civil Hospital & Medical College',
        district: 'Gandhinagar',
        designation: 'Community ASHA Coordinator',
        status: 'ACTIVE',
      },
      // Registered Patient
      {
        id: 'usr_pat_01',
        name: 'Rameshwar Sharma',
        username: 'patient',
        phone: '9876543210',
        email: 'ramesh.sharma@example.in',
        password: 'password123',
        role: 'PATIENT',
        age: 48,
        gender: 'M',
        abhaId: '14-8921-3409-7721',
        district: 'Gandhinagar',
        bloodGroup: 'O+',
        address: 'Sector 14, Gandhinagar, Gujarat 382016',
        status: 'ACTIVE',
      },
    ];

    for (const u of CANONICAL_USERS) {
      const existing = await UserModel.findOne({ $or: [{ id: u.id }, { username: u.username }] });
      if (!existing) {
        await UserModel.create(u);
      } else {
        await UserModel.updateOne({ _id: existing._id }, { $set: u });
      }
    }

    // 5. Seed Core Patient Profile
    const patientDoc = await PatientModel.findOne({ id: 'usr_pat_01' });
    if (!patientDoc) {
      await PatientModel.create({
        id: 'usr_pat_01',
        name: 'Rameshwar Sharma',
        phone: '9876543210',
        gender: 'M',
        age: 48,
        dob: '1978-04-12',
        abhaId: '14-8921-3409-7721',
        abhaVerified: true,
        address: 'Sector 14, Gandhinagar, Gujarat 382016',
        district: 'Gandhinagar',
        pincode: '382016',
      });
    }

    // 6. Seed Essential Medicine Catalog
    const medCount = await MedicineModel.countDocuments();
    if (medCount === 0) {
      await MedicineModel.insertMany([
        {
          id: 'med_01',
          facilityId: 'fac_civil_01',
          medicineName: 'Paracetamol 500mg',
          genericName: 'Paracetamol',
          category: 'Analgesics / Antipyretics',
          batchNumber: 'PCM-2026-08',
          availableQuantity: 4500,
          minimumStockThreshold: 500,
          unit: 'Tablets',
          expiryDate: '2028-06-30',
          status: 'IN_STOCK',
          lastUpdated: new Date().toISOString(),
        },
        {
          id: 'med_02',
          facilityId: 'fac_civil_01',
          medicineName: 'Amlodipine Besylate 5mg',
          genericName: 'Amlodipine',
          category: 'Cardiovascular / Anti-Hypertensive',
          batchNumber: 'AML-2026-03',
          availableQuantity: 3200,
          minimumStockThreshold: 400,
          unit: 'Tablets',
          expiryDate: '2027-12-31',
          status: 'IN_STOCK',
          lastUpdated: new Date().toISOString(),
        },
        {
          id: 'med_03',
          facilityId: 'fac_civil_01',
          medicineName: 'Telmisartan 40mg',
          genericName: 'Telmisartan',
          category: 'Cardiovascular / ARB',
          batchNumber: 'TLM-2026-11',
          availableQuantity: 2800,
          minimumStockThreshold: 350,
          unit: 'Tablets',
          expiryDate: '2028-03-31',
          status: 'IN_STOCK',
          lastUpdated: new Date().toISOString(),
        },
      ]);
    }

    // 7. Seed Real Jan Aushadhi Kendras for GPS Pharmacy Locator
    const storeCount = await MedicalStoreModel.countDocuments();
    if (storeCount === 0) {
      await MedicalStoreModel.insertMany([
        {
          id: 'store_pmbjp_raj_01',
          name: 'PMBJP Jan Aushadhi Kendra - Hospital Chowk',
          type: 'JAN_AUSHADHI',
          isJanAushadhi: true,
          hasLiveApi: true,
          licenseNumber: 'GJ-RJK-PMBJP-0102',
          area: 'Civil Hospital Chowk',
          fullAddress: 'Shop 8, Near Main Gate, PDU Civil Hospital, Hospital Chowk, Rajkot 360001',
          pincode: '360001',
          district: 'Rajkot',
          phone: '9825011223',
          whatsappPhone: '919825011223',
          timings: '8:00 AM - 10:00 PM (All 7 Days)',
          isOpenNow: true,
          rating: 4.9,
          reviewCount: 380,
          discountPercentage: 80,
          coordinates: { lat: 22.3045, lng: 70.803 },
          location: { type: 'Point', coordinates: [70.803, 22.3045] },
          stockCatalog: [
            { id: 'med_pcm_650', name: 'Tab. Paracetamol 650mg', genericName: 'Paracetamol IP 650mg', category: 'Antipyretic / Analgesic', dosage: '650 mg', status: 'IN_STOCK', quantityAvailable: 200, genericPrice: 12, brandPrice: 42, unit: 'Strip of 10 Tabs' },
            { id: 'med_panto_40', name: 'Tab. Pantoprazole 40mg', genericName: 'Pantoprazole Gastro-resistant IP 40mg', category: 'Antacid / PPI', dosage: '40 mg', status: 'IN_STOCK', quantityAvailable: 120, genericPrice: 16, brandPrice: 65, unit: 'Strip of 10 Tabs' },
            { id: 'med_amlo_5', name: 'Tab. Amlodipine 5mg', genericName: 'Amlodipine Besylate IP 5mg', category: 'Anti-Hypertensive', dosage: '5 mg', status: 'IN_STOCK', quantityAvailable: 150, genericPrice: 9, brandPrice: 38, unit: 'Strip of 10 Tabs' },
          ],
        },
        {
          id: 'store_pmbjp_01',
          name: 'Pradhan Mantri Bhartiya Janaushadhi Kendra (PMBJP) - Sector 21',
          type: 'JAN_AUSHADHI',
          isJanAushadhi: true,
          hasLiveApi: true,
          licenseNumber: 'GJ-GNR-PMBJP-0142',
          area: 'Sector 21 Market',
          fullAddress: 'Shop 14, Shopping Centre, Near SBI, Sector 21, Gandhinagar, Gujarat 382021',
          pincode: '382021',
          district: 'Gandhinagar',
          phone: '9825012345',
          whatsappPhone: '919825012345',
          timings: '8:00 AM - 10:00 PM (All 7 Days)',
          isOpenNow: true,
          rating: 4.9,
          reviewCount: 312,
          discountPercentage: 78,
          coordinates: { lat: 23.2268, lng: 72.6515 },
          location: { type: 'Point', coordinates: [72.6515, 23.2268] },
          stockCatalog: [
            { id: 'med_pcm_650', name: 'Tab. Paracetamol 650mg', genericName: 'Paracetamol IP 650mg', category: 'Antipyretic / Analgesic', dosage: '650 mg', status: 'IN_STOCK', quantityAvailable: 140, genericPrice: 12, brandPrice: 42, unit: 'Strip of 10 Tabs' },
            { id: 'med_panto_40', name: 'Tab. Pantoprazole 40mg', genericName: 'Pantoprazole Gastro-resistant IP 40mg', category: 'Antacid / PPI', dosage: '40 mg', status: 'IN_STOCK', quantityAvailable: 85, genericPrice: 16, brandPrice: 65, unit: 'Strip of 10 Tabs' },
          ],
        },
      ]);
    }

    console.log('[Seed] Database initialized cleanly with standard governance roles, facilities, and active users.');
  } catch (err) {
    console.warn('[Seed] Note during database seeding:', err);
  }
}
