import { FacilityModel } from '../models/Facility';
import { DoctorModel } from '../models/Doctor';
import { UserModel } from '../models/User';
import { RoleModel } from '../models/Role';
import { PatientModel } from '../models/Patient';
import { PatientHealthRecordModel } from '../models/HealthRecord';
import { EncounterModel } from '../models/Encounter';
import { PrescriptionModel } from '../models/Prescription';
import { DiagnosticOrderModel } from '../models/DiagnosticOrder';
import { ReferralModel } from '../models/Referral';
import { AppointmentModel, TokenModel } from '../models/Queue';
import { MedicineModel } from '../models/Medicine';
import { BloodCenterModel } from '../models/BloodCenter';
import { MedicalStoreModel } from '../models/MedicalStore';

export const SEED_ROLES = [
  {
    id: 'role_super_admin',
    code: 'SUPER_ADMIN',
    name: 'State Apex Super Administrator',
    description: 'Full state-wide administrative authority across all districts, hospitals, technical AI models, system health, and cross-district user governance.',
    level: 'STATE',
    permissions: [
      'system:manage:all',
      'district:manage:all',
      'facility:manage:all',
      'user:manage:all',
      'role:manage:all',
      'ai_models:deploy',
      'ai_models:rollback',
      'audit:read:all',
      'analytics:read:state',
      'queue:override:state',
    ],
    isSystem: true,
    isActive: true,
  },

  
  {
    id: 'role_district_admin',
    code: 'DISTRICT_ADMIN',
    name: 'District Chief Medical Administrator',
    description: 'District command authority for facility oversight, hospital staff provisioning, ambulance tracking, epidemic intelligence, and resource allocation within assigned district.',
    level: 'DISTRICT',
    permissions: [
      'district:manage:own',
      'facility:manage:district',
      'user:manage:district',
      'staff:provision:district',
      'referral:coordinate',
      'ambulance:dispatch:district',
      'epidemic:track:district',
      'inventory:reallocate:district',
      'analytics:read:district',
    ],
    isSystem: true,
    isActive: true,
  },
  {
    id: 'role_hospital_admin',
    code: 'HOSPITAL_ADMIN',
    name: 'Hospital Superintendent & Operations Admin',
    description: 'Hospital-level operational control for bed allocation, OPD department configuration, on-duty specialist rostering, and hospital staff management.',
    level: 'FACILITY',
    permissions: [
      'facility:manage:own',
      'opd:configure:facility',
      'doctor:roster:facility',
      'beds:allocate:facility',
      'staff:manage:facility',
      'queue:manage:facility',
      'inventory:manage:facility',
    ],
    isSystem: true,
    isActive: true,
  },
  {
    id: 'role_doctor',
    code: 'DOCTOR',
    name: 'Medical Officer & Specialist Physician',
    description: 'Clinical examination, live queue consultation, digital Rx prescription generation, lab investigations, e-referrals, and teleconsultation.',
    level: 'FACILITY',
    permissions: [
      'queue:call_patient',
      'consultation:write',
      'prescription:issue',
      'lab:order',
      'referral:create',
      'teleconsult:attend',
      'emr:read_write',
    ],
    isSystem: true,
    isActive: true,
  },
  {
    id: 'role_facility_staff',
    code: 'FACILITY_STAFF',
    name: 'Hospital Auxiliary Staff & Technicians',
    description: 'Hospital operations including OPD registration clerk, pharmacy dispensing, pathology laboratory testing, and triage nursing.',
    level: 'FACILITY',
    permissions: [
      'token:generate',
      'patient:register',
      'pharmacy:dispense',
      'lab:upload_result',
      'vital_signs:record',
    ],
    isSystem: true,
    isActive: true,
  },
  {
    id: 'role_asha',
    code: 'ASHA',
    name: 'ASHA & Community Health Worker',
    description: 'Grassroots community health surveillance, home health surveys, ANC/immunization tracking, emergency triage, and telehealth facilitation.',
    level: 'COMMUNITY',
    permissions: [
      'community:survey',
      'anc:track',
      'immunization:log',
      'telehealth:request',
      'emergency:flag',
    ],
    isSystem: true,
    isActive: true,
  },
  {
    id: 'role_patient',
    code: 'PATIENT',
    name: 'Citizen & Registered Patient',
    description: 'Public patient portal access for appointment scheduling, live token tracking, AI symptom triage, ABHA health locker, and medicine orders.',
    level: 'CITIZEN',
    permissions: [
      'appointment:book',
      'token:request',
      'ai_chat:use',
      'records:view_own',
      'prescription:download',
    ],
    isSystem: true,
    isActive: true,
  },
];

export const SEED_FACILITIES = [
  {
    id: 'fac_civil_01',
    name: 'Gandhinagar Civil Hospital & Medical College',
    type: 'DISTRICT_HOSPITAL',
    district: 'Gandhinagar',
    state: 'Gujarat',
    address: 'Sector 12, Gandhinagar, Gujarat 382012',
    pincode: '382012',
    contactNumber: '079-2322-1916',
    emergencyNumber: '108',
    coordinates: { lat: 23.2156, lng: 72.6369 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 15,
    totalBeds: 650,
    availableBeds: 84,
    icuBedsTotal: 60,
    icuBedsAvailable: 12,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: [
      'General Medicine',
      'Cardiology',
      'Orthopedics',
      'Pediatrics',
      'Obstetrics & Gynecology',
      'General Surgery',
      'Dermatology',
      'Ophthalmology',
      'ENT',
      'Neurology',
    ],
    departments: [
      { id: 'dep_med', name: 'General Medicine OPD', code: 'GM-OPD', activeDoctors: 4, currentWaitMinutes: 12, opdOpen: true },
      { id: 'dep_cardio', name: 'Cardiology OPD', code: 'CARD-OPD', activeDoctors: 2, currentWaitMinutes: 20, opdOpen: true },
      { id: 'dep_ortho', name: 'Orthopedics OPD', code: 'ORTHO-OPD', activeDoctors: 3, currentWaitMinutes: 15, opdOpen: true },
      { id: 'dep_pedia', name: 'Pediatrics OPD', code: 'PED-OPD', activeDoctors: 2, currentWaitMinutes: 10, opdOpen: true },
      { id: 'dep_obg', name: 'Obstetrics & Gynecology OPD', code: 'OBG-OPD', activeDoctors: 3, currentWaitMinutes: 18, opdOpen: true },
      { id: 'dep_surg', name: 'General Surgery OPD', code: 'SURG-OPD', activeDoctors: 2, currentWaitMinutes: 25, opdOpen: true },
      { id: 'dep_derma', name: 'Dermatology OPD', code: 'DERM-OPD', activeDoctors: 2, currentWaitMinutes: 15, opdOpen: true },
      { id: 'dep_opht', name: 'Ophthalmology OPD', code: 'OPHT-OPD', activeDoctors: 2, currentWaitMinutes: 15, opdOpen: true },
    ],
  },
  {
    id: 'fac_un_mehta',
    name: 'U. N. Mehta Institute of Cardiology & Research Centre',
    type: 'SPECIALTY_HOSPITAL',
    district: 'Ahmedabad',
    state: 'Gujarat',
    address: 'Civil Hospital Campus, Asarwa, Ahmedabad 380016',
    pincode: '380016',
    contactNumber: '079-2268-4200',
    emergencyNumber: '108',
    coordinates: { lat: 23.0524, lng: 72.5932 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 10,
    totalBeds: 1251,
    availableBeds: 142,
    icuBedsTotal: 180,
    icuBedsAvailable: 34,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: ['Cardiology', 'Cardiac Surgery', 'Interventional Cardiology', 'Pediatric Cardiology', 'Cath Lab', 'Emergency CCU'],
    departments: [
      { id: 'dep_cardio_apex', name: '24x7 Cath Lab & Emergency Cardiology', code: 'CARD-APEX', activeDoctors: 6, currentWaitMinutes: 10, opdOpen: true },
      { id: 'dep_cts', name: 'Cardiothoracic & Vascular Surgery (CTVS)', code: 'CTVS-OPD', activeDoctors: 4, currentWaitMinutes: 15, opdOpen: true },
    ],
  },
  {
    id: 'fac_ikdrc',
    name: 'Institute of Kidney Diseases and Research Centre (IKDRC)',
    type: 'SPECIALTY_HOSPITAL',
    district: 'Ahmedabad',
    state: 'Gujarat',
    address: 'Civil Hospital Campus, Asarwa, Ahmedabad 380016',
    pincode: '380016',
    contactNumber: '079-2268-7000',
    emergencyNumber: '108',
    coordinates: { lat: 23.0538, lng: 72.5945 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 15,
    totalBeds: 450,
    availableBeds: 58,
    icuBedsTotal: 50,
    icuBedsAvailable: 14,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: ['Nephrology', 'Urology', 'Dialysis', 'Kidney Transplant', 'Renal Medicine', 'Pediatric Nephrology'],
    departments: [
      { id: 'dep_nephro', name: 'Nephrology & Hemodialysis Unit', code: 'NEPH-OPD', activeDoctors: 4, currentWaitMinutes: 12, opdOpen: true },
      { id: 'dep_uro', name: 'Urology & Kidney Stone Clinic', code: 'URO-OPD', activeDoctors: 3, currentWaitMinutes: 18, opdOpen: true },
    ],
  },
  {
    id: 'fac_gcri',
    name: 'The Gujarat Cancer & Research Institute (GCRI)',
    type: 'SPECIALTY_HOSPITAL',
    district: 'Ahmedabad',
    state: 'Gujarat',
    address: 'M. P. Shah Cancer Hospital, Civil Hospital Campus, Asarwa, Ahmedabad 380016',
    pincode: '380016',
    contactNumber: '079-2268-8000',
    emergencyNumber: '108',
    coordinates: { lat: 23.0545, lng: 72.5928 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 20,
    totalBeds: 650,
    availableBeds: 72,
    icuBedsTotal: 40,
    icuBedsAvailable: 9,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: ['Oncology', 'Medical Oncology', 'Surgical Oncology', 'Radiation Oncology', 'Chemotherapy Daycare', 'Palliative Care'],
    departments: [
      { id: 'dep_med_onc', name: 'Medical Oncology & Chemotherapy', code: 'ONC-MED', activeDoctors: 5, currentWaitMinutes: 15, opdOpen: true },
      { id: 'dep_surg_onc', name: 'Surgical Oncology OPD', code: 'ONC-SURG', activeDoctors: 4, currentWaitMinutes: 20, opdOpen: true },
    ],
  },
  {
    id: 'fac_mandj_eye',
    name: 'M & J Western Regional Institute of Ophthalmology',
    type: 'SPECIALTY_HOSPITAL',
    district: 'Ahmedabad',
    state: 'Gujarat',
    address: 'Civil Hospital Campus, Asarwa, Ahmedabad 380016',
    pincode: '380016',
    contactNumber: '079-2268-2000',
    emergencyNumber: '108',
    coordinates: { lat: 23.0518, lng: 72.5919 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 10,
    totalBeds: 250,
    availableBeds: 45,
    icuBedsTotal: 10,
    icuBedsAvailable: 4,
    oxygenAvailable: true,
    bloodBankAvailable: false,
    ambulanceAvailable: true,
    specialties: ['Ophthalmology', 'Retina & Vitreous Clinic', 'Cornea Transplant', 'Glaucoma Care', 'Pediatric Ophthalmology', 'Cataract Surgery'],
    departments: [
      { id: 'dep_eye_opd', name: 'Comprehensive Eye OPD & Refraction', code: 'EYE-OPD', activeDoctors: 4, currentWaitMinutes: 10, opdOpen: true },
      { id: 'dep_retina', name: 'Retina & Laser Unit', code: 'RET-OPD', activeDoctors: 2, currentWaitMinutes: 15, opdOpen: true },
    ],
  },
  {
    id: 'fac_women_child',
    name: 'District Women & Child Hospital (MCH Wing)',
    type: 'DISTRICT_HOSPITAL',
    district: 'Gandhinagar',
    state: 'Gujarat',
    address: 'Sector 24, Gandhinagar, Gujarat 382024',
    pincode: '382024',
    contactNumber: '079-2323-8890',
    emergencyNumber: '108',
    coordinates: { lat: 23.2384, lng: 72.6482 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 12,
    totalBeds: 200,
    availableBeds: 36,
    icuBedsTotal: 25,
    icuBedsAvailable: 8,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: ['Obstetrics & Gynecology', 'Maternal Health', 'Pediatrics', 'Neonatal Intensive Care (NICU)', 'Antenatal Care (ANC)', 'Family Welfare'],
    departments: [
      { id: 'dep_mch_obg', name: 'Antenatal & Maternal Wing', code: 'MCH-OBG', activeDoctors: 4, currentWaitMinutes: 12, opdOpen: true },
      { id: 'dep_mch_nicu', name: 'Neonatal & Pediatric Care', code: 'MCH-NICU', activeDoctors: 3, currentWaitMinutes: 8, opdOpen: true },
    ],
  },
  {
    id: 'fac_apex_trauma',
    name: 'Apex Trauma & Orthopedic Emergency Centre',
    type: 'SPECIALTY_HOSPITAL',
    district: 'Gandhinagar',
    state: 'Gujarat',
    address: 'Near GH-Road Bypass, Sector 7, Gandhinagar 382007',
    pincode: '382007',
    contactNumber: '079-2324-5566',
    emergencyNumber: '108',
    coordinates: { lat: 23.2201, lng: 72.6289 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 8,
    totalBeds: 180,
    availableBeds: 29,
    icuBedsTotal: 35,
    icuBedsAvailable: 11,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: ['Orthopedics', 'Trauma Surgery', 'Neurotrauma', 'Emergency Medicine', 'Joint Replacement', 'Fracture Care', 'Spine Surgery'],
    departments: [
      { id: 'dep_apex_trauma', name: '24x7 Red-Zone Trauma Casualty', code: 'TRAUMA-RED', activeDoctors: 5, currentWaitMinutes: 5, opdOpen: true },
      { id: 'dep_ortho_clinic', name: 'Orthopedic Fracture & Joint Clinic', code: 'ORTHO-CLINIC', activeDoctors: 3, currentWaitMinutes: 12, opdOpen: true },
    ],
  },
  {
    id: 'fac_gmers_sola',
    name: 'GMERS Medical College & Civil Hospital Sola',
    type: 'MEDICAL_COLLEGE',
    district: 'Ahmedabad',
    state: 'Gujarat',
    address: 'SG Highway, Sola, Ahmedabad, Gujarat 380060',
    pincode: '380060',
    contactNumber: '079-2766-1022',
    emergencyNumber: '108',
    coordinates: { lat: 23.0833, lng: 72.5255 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 14,
    totalBeds: 720,
    availableBeds: 95,
    icuBedsTotal: 55,
    icuBedsAvailable: 15,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: ['General Medicine', 'Pediatrics', 'Pulmonology', 'Orthopedics', 'General Surgery', 'Dermatology', 'ENT', 'Emergency Medicine'],
    departments: [
      { id: 'dep_sola_med', name: 'General Medicine & Infectious Diseases', code: 'SOLA-GM', activeDoctors: 4, currentWaitMinutes: 12, opdOpen: true },
      { id: 'dep_sola_ped', name: 'Pediatric Care & Immunization', code: 'SOLA-PED', activeDoctors: 3, currentWaitMinutes: 10, opdOpen: true },
    ],
  },
  {
    id: 'fac_pet_04',
    name: 'Pethapur Primary Health Centre',
    type: 'PHC',
    district: 'Gandhinagar',
    state: 'Gujarat',
    address: 'Near Gram Panchayat, Pethapur, Gandhinagar 382610',
    pincode: '382610',
    contactNumber: '079-2329-0123',
    emergencyNumber: '108',
    coordinates: { lat: 23.2842, lng: 72.6841 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: false,
    currentWaitTimeMinutes: 8,
    totalBeds: 12,
    availableBeds: 5,
    icuBedsTotal: 0,
    icuBedsAvailable: 0,
    oxygenAvailable: true,
    bloodBankAvailable: false,
    ambulanceAvailable: true,
    specialties: ['General Medicine', 'Maternal Health', 'Pediatrics'],
    departments: [
      { id: 'dep_med', name: 'General Medicine OPD', code: 'GM-OPD', activeDoctors: 2, currentWaitMinutes: 8, opdOpen: true },
      { id: 'dep_obg', name: 'Maternal Care', code: 'MAT-OPD', activeDoctors: 1, currentWaitMinutes: 10, opdOpen: true },
    ],
  },
  {
    id: 'fac_chc_02',
    name: 'Mansa Community Health Centre',
    type: 'CHC',
    district: 'Gandhinagar',
    state: 'Gujarat',
    address: 'Station Road, Mansa, Gujarat 382845',
    pincode: '382845',
    contactNumber: '02763-272022',
    emergencyNumber: '108',
    coordinates: { lat: 23.4287, lng: 72.6621 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 12,
    totalBeds: 45,
    availableBeds: 16,
    icuBedsTotal: 4,
    icuBedsAvailable: 2,
    oxygenAvailable: true,
    bloodBankAvailable: false,
    ambulanceAvailable: true,
    specialties: ['General Medicine', 'General Surgery', 'Obstetrics & Gynecology', 'Pediatrics'],
    departments: [
      { id: 'dep_med', name: 'General Medicine OPD', code: 'GM-OPD', activeDoctors: 2, currentWaitMinutes: 10, opdOpen: true },
      { id: 'dep_surg', name: 'General Surgery OPD', code: 'SURG-OPD', activeDoctors: 1, currentWaitMinutes: 15, opdOpen: true },
    ],
  },
];

export const SEED_DOCTORS = [
  {
    id: 'doc_patel_01',
    name: 'Dr. Arvind Patel',
    qualification: 'MBBS, MD (General Medicine)',
    specialty: 'General Medicine',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543201',
    email: 'dr.arvind.patel@gujarat.health.gov.in',
    opdSchedule: 'Mon-Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'Room 4 (1st Floor)',
    patientsToday: 14,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-28491',
  },
  {
    id: 'doc_cardio_01',
    name: 'Dr. K. P. Trivedi',
    qualification: 'MD, DM (Cardiology)',
    specialty: 'Cardiology',
    facilityId: 'fac_un_mehta',
    facilityName: 'U. N. Mehta Institute of Cardiology & Research Centre',
    status: 'ON_DUTY',
    phone: '9876543204',
    email: 'dr.kp.trivedi@gujarat.health.gov.in',
    opdSchedule: 'Mon-Sat: 9:00 AM - 2:00 PM (24x7 Emergency CCU)',
    opdRoom: 'Cardio Wing - Room 12',
    patientsToday: 9,
    teleconsultEnabled: true,
    district: 'Ahmedabad',
    registrationNumber: 'G-15201',
  },
  {
    id: 'doc_nephro_01',
    name: 'Dr. Pratik Dave',
    qualification: 'MD, DM (Nephrology & Renal Dialysis)',
    specialty: 'Nephrology',
    facilityId: 'fac_ikdrc',
    facilityName: 'Institute of Kidney Diseases and Research Centre (IKDRC)',
    status: 'ON_DUTY',
    phone: '9876543214',
    email: 'dr.pratik.dave@gujarat.health.gov.in',
    opdSchedule: 'Mon-Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'Renal Block - Room 7',
    patientsToday: 16,
    teleconsultEnabled: true,
    district: 'Ahmedabad',
    registrationNumber: 'G-29402',
  },
  {
    id: 'doc_oncology_01',
    name: 'Dr. Meera Shah',
    qualification: 'MD, DM (Medical Oncology)',
    specialty: 'Oncology',
    facilityId: 'fac_gcri',
    facilityName: 'The Gujarat Cancer & Research Institute (GCRI)',
    status: 'ON_DUTY',
    phone: '9876543215',
    email: 'dr.meera.shah@gujarat.health.gov.in',
    opdSchedule: 'Mon-Fri: 9:00 AM - 2:00 PM',
    opdRoom: 'Oncology Wing - Room 3',
    patientsToday: 11,
    teleconsultEnabled: true,
    district: 'Ahmedabad',
    registrationNumber: 'G-33108',
  },
  {
    id: 'doc_eye_01',
    name: 'Dr. Hiren Joshi',
    qualification: 'MS (Ophthalmology), FICO',
    specialty: 'Ophthalmology',
    facilityId: 'fac_mandj_eye',
    facilityName: 'M & J Western Regional Institute of Ophthalmology',
    status: 'ON_DUTY',
    phone: '9876543216',
    email: 'dr.hiren.joshi@gujarat.health.gov.in',
    opdSchedule: 'Mon-Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'Eye OPD - Room 10',
    patientsToday: 18,
    teleconsultEnabled: true,
    district: 'Ahmedabad',
    registrationNumber: 'G-24819',
  },
  {
    id: 'doc_ortho_01',
    name: 'Dr. Rajesh Varma',
    qualification: 'MS (Orthopedics), M.Ch',
    specialty: 'Orthopedics',
    facilityId: 'fac_apex_trauma',
    facilityName: 'Apex Trauma & Orthopedic Emergency Centre',
    status: 'ON_DUTY',
    phone: '9876543205',
    email: 'dr.rajesh.varma@gujarat.health.gov.in',
    opdSchedule: 'Mon-Sat: 9:00 AM - 1:00 PM (24x7 Trauma Casualty)',
    opdRoom: 'Trauma Wing - Room 8',
    patientsToday: 12,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-22109',
  },
  {
    id: 'doc_pedia_01',
    name: 'Dr. Sangeeta Rao',
    qualification: 'MD (Pediatrics), DCH',
    specialty: 'Pediatrics',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543206',
    email: 'dr.sangeeta.rao@gujarat.health.gov.in',
    opdSchedule: 'Mon-Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'Child Health - Room 5',
    patientsToday: 15,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-31088',
  },
  {
    id: 'doc_obg_01',
    name: 'Dr. Bhavna Desai',
    qualification: 'MD (Obstetrics & Gynecology), DGO',
    specialty: 'Obstetrics & Gynecology',
    facilityId: 'fac_women_child',
    facilityName: 'District Women & Child Hospital (MCH Wing)',
    status: 'ON_DUTY',
    phone: '9876543207',
    email: 'dr.bhavna.desai@gujarat.health.gov.in',
    opdSchedule: 'Mon-Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'Maternity Wing - Room 10',
    patientsToday: 19,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-18934',
  },
  {
    id: 'doc_mehta_02',
    name: 'Dr. Vikramaditya Mehta',
    qualification: 'MD (Gen Med), DNB',
    specialty: 'General Medicine',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543202',
    email: 'dr.v.mehta@gujarat.health.gov.in',
    opdSchedule: 'Mon, Wed, Fri: 9:00 AM - 2:00 PM',
    opdRoom: 'Room 6 (1st Floor)',
    patientsToday: 11,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-19342',
  },
  {
    id: 'doc_ananya_03',
    name: 'Dr. Ananya Patel',
    qualification: 'MBBS, DNB (Internal Medicine)',
    specialty: 'General Medicine',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543203',
    email: 'dr.ananya.patel@gujarat.health.gov.in',
    opdSchedule: 'Tue, Thu, Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'Room 2 (Ground Floor)',
    patientsToday: 8,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-34102',
  },
  {
    id: 'doc_cardio_01',
    name: 'Dr. K. P. Trivedi',
    qualification: 'MD, DM (Cardiology)',
    specialty: 'Cardiology',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543204',
    email: 'dr.kp.trivedi@gujarat.health.gov.in',
    opdSchedule: 'Mon-Fri: 10:00 AM - 2:00 PM',
    opdRoom: 'Cardio Wing - Room 12',
    patientsToday: 9,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-15201',
  },
  {
    id: 'doc_ortho_01',
    name: 'Dr. Rajesh Varma',
    qualification: 'MS (Orthopedics), M.Ch',
    specialty: 'Orthopedics',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543205',
    email: 'dr.rajesh.varma@gujarat.health.gov.in',
    opdSchedule: 'Mon, Tue, Thu, Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'Ortho Wing - Room 8',
    patientsToday: 12,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-22109',
  },
  {
    id: 'doc_pedia_01',
    name: 'Dr. Sangeeta Rao',
    qualification: 'MD (Pediatrics), DCH',
    specialty: 'Pediatrics',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543206',
    email: 'dr.sangeeta.rao@gujarat.health.gov.in',
    opdSchedule: 'Mon-Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'Child Health - Room 5',
    patientsToday: 15,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-31088',
  },
  {
    id: 'doc_pet_01',
    name: 'Dr. Suresh Rawal',
    qualification: 'MBBS',
    specialty: 'General Medicine',
    facilityId: 'fac_pet_04',
    facilityName: 'Pethapur Primary Health Centre',
    status: 'ON_DUTY',
    phone: '9876543208',
    email: 'dr.suresh.rawal@gujarat.health.gov.in',
    opdSchedule: 'Mon-Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'OPD Room 1',
    patientsToday: 7,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-33120',
  },
];

export async function seedInitialDatabase(): Promise<void> {
  try {
    // 1. Seed Facilities
    const facCount = await FacilityModel.countDocuments();
    if (facCount === 0) {
      console.log('[Seed] Seeding initial healthcare facilities...');
      await FacilityModel.insertMany(SEED_FACILITIES);
    }

    // 2. Seed Doctors
    const docCount = await DoctorModel.countDocuments();
    if (docCount === 0) {
      console.log('[Seed] Seeding initial hospital doctors...');
      await DoctorModel.insertMany(SEED_DOCTORS);
    }

    // 3. Seed Patient User in UserModel
    let patientUser = await UserModel.findOne({ role: 'PATIENT', phone: '9876543210' });
    if (!patientUser) {
      console.log('[Seed] Creating default Patient user in UserModel...');
      patientUser = await UserModel.create({
        id: 'usr_pat_01',
        name: 'Rameshwar Sharma',
        phone: '9876543210',
        email: 'ramesh.sharma@example.in',
        password: 'password123',
        role: 'PATIENT',
        age: 48,
        gender: 'M',
        abhaId: '14-8921-3409-7721',
        district: 'Gandhinagar',
        bloodGroup: 'O+',
        address: 'Sector 14, Gandhinagar, Gujarat 382016',
        emergencyContactName: 'Savitri Sharma',
        emergencyContactPhone: '9876543210',
        preferredLanguage: 'en',
      });
    }

    // Ensure pat_01 alias exists
    const patAlias = await UserModel.findOne({ id: 'pat_01' });
    if (!patAlias) {
      await UserModel.create({
        id: 'pat_01',
        name: 'Rameshwar Sharma',
        phone: '9876543210',
        email: 'pat01@example.in',
        password: 'password123',
        role: 'PATIENT',
        age: 48,
        gender: 'M',
        abhaId: '14-8921-3409-7721',
        district: 'Gandhinagar',
      });
    }

    // 4. Seed Registered Patient in PatientModel
    const patientDoc = await PatientModel.findOne({ id: 'usr_pat_01' });
    if (!patientDoc) {
      console.log('[Seed] Creating default Patient in PatientModel...');
      await PatientModel.create({
        id: 'usr_pat_01',
        name: 'Rameshwar Sharma',
        phone: '9876543210',
        gender: 'M',
        age: 48,
        dob: '1978-04-12',
        abhaId: '14-8921-3409-7721',
        abhaVerified: true,
        address: 'Sector 14, Gandhinagar, Gujarat 382016',
        district: 'Gandhinagar',
        pincode: '382016',
        emergencyContact: {
          name: 'Savitri Sharma',
          phone: '9876543210',
          relationship: 'Spouse',
        },
        registeredAt: new Date(Date.now() - 30 * 86400000).toISOString(),
        lastVisitAt: new Date().toISOString(),
      });
    }

    // 5. Seed Patient Health Record (EHR) & Clinical Timeline
    const healthRecord = await PatientHealthRecordModel.findOne({ patientId: 'usr_pat_01' });
    if (!healthRecord) {
      console.log('[Seed] Creating default Patient Health Record with rich timeline...');
      await PatientHealthRecordModel.create({
        patientId: 'usr_pat_01',
        name: 'Rameshwar Sharma',
        age: 48,
        gender: 'M',
        phone: '9876543210',
        abhaId: '14-8921-3409-7721',
        bloodGroup: 'O+',
        allergies: ['Penicillin'],
        chronicConditions: ['Hypertension'],
        timeline: [
          {
            id: 'tl_01',
            date: '2026-09-12',
            eventType: 'ENCOUNTER',
            title: 'OPD Consultation - Hypertension Follow-up',
            facilityName: 'Gandhinagar Civil Hospital & Medical College',
            doctorName: 'Dr. Arvind Patel',
            summary: 'Blood pressure reviewed. Target BP achieved with current dosage. Advised low salt diet and regular morning walk.',
            details: {
              vitals: { systolicBp: 126, diastolicBp: 82, pulseRate: 74, spO2: 99 },
              diagnosis: 'Essential Hypertension (ICD-10 I10)',
            },
          },
          {
            id: 'tl_02',
            date: '2026-09-12',
            eventType: 'PRESCRIPTION',
            title: 'Prescription Issued - Anti-Hypertensive Regimen',
            facilityName: 'Gandhinagar Civil Hospital & Medical College',
            doctorName: 'Dr. Arvind Patel',
            summary: 'Prescribed Amlodipine 5mg and Telmisartan 40mg for 30 days.',
            details: {
              prescriptionId: 'rx_2026_01',
              medicationsCount: 2,
            },
          },
          {
            id: 'tl_03',
            date: '2026-09-10',
            eventType: 'LAB_REPORT',
            title: 'Diagnostic Report - Lipid Profile & Fasting Blood Sugar',
            facilityName: 'Gandhinagar Civil Hospital Central Diagnostic Lab',
            doctorName: 'Dr. Arvind Patel',
            summary: 'Cholesterol Total: 188 mg/dL (Normal), Triglycerides: 142 mg/dL (Normal), Fasting Sugar: 96 mg/dL (Normal).',
            details: {
              orderId: 'lab_ord_01',
              status: 'REPORT_READY',
            },
          },
          {
            id: 'tl_04',
            date: '2026-08-25',
            eventType: 'REFERRAL',
            title: 'Inter-Facility Referral - Cardiology Evaluation',
            facilityName: 'Pethapur Primary Health Centre -> Gandhinagar Civil Hospital',
            doctorName: 'Dr. Suresh Rawal',
            summary: 'Referred from Pethapur PHC for detailed cardiac evaluation and echocardiography.',
            details: {
              referralId: 'ref_2026_01',
              referralCode: 'REF-2026-0842',
              priority: 'URGENT',
            },
          },
          {
            id: 'tl_05',
            date: '2026-08-20',
            eventType: 'VITALS',
            title: 'Community Screening Vitals Recorded by ASHA',
            facilityName: 'Pethapur Sub-Centre Area',
            doctorName: 'Sunita Devi (ASHA Worker)',
            summary: 'BP: 138/88 mmHg, Pulse: 78 bpm, Random Blood Sugar: 112 mg/dL.',
            details: {
              recordedBy: 'Sunita Devi (ASHA)',
              riskLevel: 'NEEDS_ATTENTION',
            },
          },
        ],
      });
    }

    // 6. Seed Prescriptions
    const rxCount = await PrescriptionModel.countDocuments();
    if (rxCount === 0) {
      console.log('[Seed] Seeding sample Prescriptions...');
      await PrescriptionModel.insertMany([
        {
          id: 'rx_2026_01',
          encounterId: 'enc_sample_01',
          patientId: 'usr_pat_01',
          patientName: 'Rameshwar Sharma',
          doctorId: 'doc_patel_01',
          doctorName: 'Dr. Arvind Patel',
          facilityId: 'fac_civil_01',
          facilityName: 'Gandhinagar Civil Hospital & Medical College',
          issuedAt: new Date(Date.now() - 86400000).toISOString(),
          diagnosisSummary: 'Essential Hypertension & Mild Dyslipidemia',
          items: [
            {
              id: 'item_01',
              medicineName: 'Amlodipine Besylate 5mg',
              genericName: 'Amlodipine',
              dosage: '1 Tablet',
              frequency: 'Once Daily (Morning after breakfast)',
              duration: '30 Days',
              route: 'Oral',
              instructions: 'Take regularly at the same time each day',
              dispensedStatus: 'DISPENSED',
              dispensedQuantity: 30,
              totalQuantity: 30,
            },
            {
              id: 'item_02',
              medicineName: 'Telmisartan 40mg',
              genericName: 'Telmisartan',
              dosage: '1 Tablet',
              frequency: 'Once Daily (Night before sleep)',
              duration: '30 Days',
              route: 'Oral',
              instructions: 'Maintain low salt intake with medication',
              dispensedStatus: 'DISPENSED',
              dispensedQuantity: 30,
              totalQuantity: 30,
            },
            {
              id: 'item_03',
              medicineName: 'Paracetamol 500mg',
              genericName: 'Paracetamol',
              dosage: '1 Tablet',
              frequency: 'SOS (As needed for headache/body ache)',
              duration: '5 Days',
              route: 'Oral',
              instructions: 'Maximum 3 tablets per 24 hours',
              dispensedStatus: 'PENDING',
              dispensedQuantity: 0,
              totalQuantity: 10,
            },
          ],
          status: 'PARTIALLY_DISPENSED',
          pharmacyNotes: 'Amlodipine and Telmisartan dispensed by Civil Hospital Pharmacy counter.',
        },
        {
          id: 'rx_2026_02',
          encounterId: 'enc_sample_02',
          patientId: 'usr_pat_01',
          patientName: 'Rameshwar Sharma',
          doctorId: 'doc_pet_01',
          doctorName: 'Dr. Suresh Rawal',
          facilityId: 'fac_pet_04',
          facilityName: 'Pethapur Primary Health Centre',
          issuedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
          diagnosisSummary: 'Acute Pharyngitis & Seasonal Viral Cold',
          items: [
            {
              id: 'item_04',
              medicineName: 'Cetirizine Hydrochloride 10mg',
              genericName: 'Cetirizine',
              dosage: '1 Tablet',
              frequency: 'Once Daily at bedtime',
              duration: '5 Days',
              route: 'Oral',
              instructions: 'May cause mild drowsiness',
              dispensedStatus: 'DISPENSED',
              dispensedQuantity: 5,
              totalQuantity: 5,
            },
            {
              id: 'item_05',
              medicineName: 'Vitamin C & Zinc Chewable',
              genericName: 'Ascorbic Acid + Zinc',
              dosage: '1 Chewable Tab',
              frequency: 'Twice daily after meals',
              duration: '10 Days',
              route: 'Oral',
              instructions: 'Chew thoroughly before swallowing',
              dispensedStatus: 'DISPENSED',
              dispensedQuantity: 20,
              totalQuantity: 20,
            },
          ],
          status: 'DISPENSED',
          pharmacyNotes: 'Completed full course at Pethapur PHC dispensary.',
        },
      ]);
    }

    // 7. Seed Diagnostic Orders
    const labCount = await DiagnosticOrderModel.countDocuments();
    if (labCount === 0) {
      console.log('[Seed] Seeding sample Diagnostic Orders...');
      await DiagnosticOrderModel.insertMany([
        {
          id: 'lab_ord_01',
          encounterId: 'enc_sample_01',
          patientId: 'usr_pat_01',
          patientName: 'Rameshwar Sharma',
          patientAge: 48,
          patientGender: 'M',
          patientPhone: '9876543210',
          patientAbha: '14-8921-3409-7721',
          testName: 'Complete Lipid Profile (Serum)',
          testCategory: 'BIOCHEMISTRY',
          priority: 'ROUTINE',
          orderedBy: 'Dr. Arvind Patel',
          orderedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
          facilityId: 'fac_civil_01',
          facilityName: 'Gandhinagar Civil Hospital Central Diagnostic Lab',
          status: 'REPORT_READY',
          sampleId: 'SMP-8901',
          sampleType: 'Venous Whole Blood / Serum',
          containerType: 'Gold Top (SST) Vacutainer',
          barcodeNumber: 'BAR-449102',
          sampleCollectedAt: new Date(Date.now() - 2 * 86400000 + 3600000).toISOString(),
          sampleReceivedAt: new Date(Date.now() - 2 * 86400000 + 5400000).toISOString(),
          completedAt: new Date(Date.now() - 86400000).toISOString(),
          technicianName: 'Priya Shah (Senior Lab Technician)',
          resultParameters: [
            { name: 'Total Cholesterol', value: '188', unit: 'mg/dL', referenceRange: '125 - 200', status: 'NORMAL' },
            { name: 'HDL Cholesterol (Good)', value: '46', unit: 'mg/dL', referenceRange: '40 - 60', status: 'NORMAL' },
            { name: 'LDL Cholesterol (Direct)', value: '114', unit: 'mg/dL', referenceRange: '< 130', status: 'NORMAL' },
            { name: 'Triglycerides', value: '142', unit: 'mg/dL', referenceRange: '< 150', status: 'NORMAL' },
            { name: 'VLDL Cholesterol', value: '28', unit: 'mg/dL', referenceRange: '10 - 30', status: 'NORMAL' },
          ],
          resultSummary: 'Lipid profile parameters are within optimal biological target ranges.',
          isAbnormal: false,
        },
        {
          id: 'lab_ord_02',
          encounterId: 'enc_sample_01',
          patientId: 'usr_pat_01',
          patientName: 'Rameshwar Sharma',
          patientAge: 48,
          patientGender: 'M',
          patientPhone: '9876543210',
          patientAbha: '14-8921-3409-7721',
          testName: 'Complete Blood Count (CBC with Automated Differential)',
          testCategory: 'HEMATOLOGY',
          priority: 'ROUTINE',
          orderedBy: 'Dr. Arvind Patel',
          orderedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
          facilityId: 'fac_civil_01',
          facilityName: 'Gandhinagar Civil Hospital Central Diagnostic Lab',
          status: 'REPORT_READY',
          sampleId: 'SMP-8902',
          sampleType: 'Whole Blood (EDTA)',
          containerType: 'Lavender Top Vacutainer',
          barcodeNumber: 'BAR-449103',
          completedAt: new Date(Date.now() - 86400000).toISOString(),
          technicianName: 'Priya Shah (Senior Lab Technician)',
          resultParameters: [
            { name: 'Hemoglobin (Hb)', value: '14.2', unit: 'g/dL', referenceRange: '13.0 - 17.0', status: 'NORMAL' },
            { name: 'Total Leukocyte Count (TLC)', value: '7,400', unit: '/cu.mm', referenceRange: '4,000 - 11,000', status: 'NORMAL' },
            { name: 'Platelet Count', value: '245,000', unit: '/cu.mm', referenceRange: '150,000 - 450,000', status: 'NORMAL' },
            { name: 'Packed Cell Volume (PCV)', value: '42.8', unit: '%', referenceRange: '40 - 50', status: 'NORMAL' },
          ],
          resultSummary: 'Hematological parameters normal. No signs of infection or anemia.',
          isAbnormal: false,
        },
      ]);
    }

    // 8. Seed Referrals
    const refCount = await ReferralModel.countDocuments();
    if (refCount === 0) {
      console.log('[Seed] Seeding sample Clinical Referrals...');
      await ReferralModel.insertMany([
        {
          id: 'ref_2026_01',
          referralCode: 'REF-2026-0842',
          patientId: 'usr_pat_01',
          patientName: 'Rameshwar Sharma',
          patientAge: 48,
          patientGender: 'M',
          patientPhone: '9876543210',
          abhaId: '14-8921-3409-7721',
          fromFacilityId: 'fac_pet_04',
          fromFacilityName: 'Pethapur Primary Health Centre',
          fromDoctorId: 'doc_pet_01',
          fromDoctorName: 'Dr. Suresh Rawal',
          toFacilityId: 'fac_civil_01',
          toFacilityName: 'Gandhinagar Civil Hospital & Medical College',
          toSpecialty: 'General Medicine',
          toDoctorId: 'doc_patel_01',
          toDoctorName: 'Dr. Arvind Patel',
          reasonForReferral: 'Hypertension Management & Specialist Cardiology Evaluation',
          clinicalSummary: 'Patient presented at Pethapur PHC with persistent elevated blood pressure (145/95 mmHg) and episodic dizziness. Referred for specialist titration and echo.',
          priority: 'URGENT',
          status: 'ACCEPTED',
          slaDeadline: new Date(Date.now() + 48 * 3600000).toISOString(),
          slaBreached: false,
          appointmentId: 'apt_sample_01',
          appointmentSlot: '10:30 AM',
          tokenId: 'tok_01',
          tokenNumber: 'OPD-28',
          events: [
            {
              id: 'ev_01',
              status: 'CREATED',
              timestamp: new Date(Date.now() - 3 * 86400000).toISOString(),
              actorName: 'Dr. Suresh Rawal',
              actorRole: 'DOCTOR',
              facilityName: 'Pethapur Primary Health Centre',
              notes: 'Referral generated for Civil Hospital Cardiology OPD',
            },
            {
              id: 'ev_02',
              status: 'SENT',
              timestamp: new Date(Date.now() - 3 * 86400000 + 1800000).toISOString(),
              actorName: 'HealthConnect Referral Engine',
              actorRole: 'SYSTEM',
              facilityName: 'Gandhinagar Health Network',
              notes: 'Electronic Referral transmitted via NHA FHIR Gateway',
            },
            {
              id: 'ev_03',
              status: 'ACCEPTED',
              timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
              actorName: 'Dr. Arvind Patel',
              actorRole: 'DOCTOR',
              facilityName: 'Gandhinagar Civil Hospital',
              notes: 'Referral accepted. Priority OPD slot confirmed in Room 4.',
            },
          ],
          createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
          updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
        },
      ]);
    }

    // 9. Seed Queue Tokens
    const tokCount = await TokenModel.countDocuments();
    if (tokCount === 0) {
      console.log('[Seed] Seeding sample OPD Queue Tokens...');
      await TokenModel.insertMany([
        {
          id: 'tok_01',
          tokenNumber: 'OPD-28',
          patientId: 'usr_pat_01',
          patientName: 'Rameshwar Sharma',
          patientAge: 48,
          patientGender: 'M',
          patientPhone: '9876543210',
          facilityId: 'fac_civil_01',
          facilityName: 'Gandhinagar Civil Hospital & Medical College',
          departmentId: 'dep_med',
          departmentName: 'General Medicine OPD',
          doctorId: 'doc_patel_01',
          doctorName: 'Dr. Arvind Patel',
          roomNumber: 'Room 4 (1st Floor)',
          counter: 'Counter 2',
          status: 'WAITING',
          priority: 'ROUTINE',
          positionInQueue: 3,
          estimatedWaitMinutes: 15,
          referralId: 'ref_2026_01',
          referralCode: 'REF-2026-0842',
          createdAt: new Date().toISOString(),
        },
        {
          id: 'tok_02',
          tokenNumber: 'OPD-26',
          patientId: 'usr_pat_02',
          patientName: 'Kamlaben Vaghela',
          patientAge: 48,
          patientGender: 'F',
          patientPhone: '9898012345',
          facilityId: 'fac_civil_01',
          facilityName: 'Gandhinagar Civil Hospital & Medical College',
          departmentId: 'dep_med',
          departmentName: 'General Medicine OPD',
          doctorId: 'doc_patel_01',
          doctorName: 'Dr. Arvind Patel',
          roomNumber: 'Room 4 (1st Floor)',
          counter: 'Counter 2',
          status: 'CALLED',
          priority: 'ROUTINE',
          positionInQueue: 1,
          estimatedWaitMinutes: 2,
          createdAt: new Date(Date.now() - 1800000).toISOString(),
          calledAt: new Date(Date.now() - 120000).toISOString(),
        },
        {
          id: 'tok_03',
          tokenNumber: 'OPD-27',
          patientId: 'usr_pat_03',
          patientName: 'Sanjaybhai Shah',
          patientAge: 38,
          patientGender: 'M',
          patientPhone: '9825098765',
          facilityId: 'fac_civil_01',
          facilityName: 'Gandhinagar Civil Hospital & Medical College',
          departmentId: 'dep_med',
          departmentName: 'General Medicine OPD',
          doctorId: 'doc_patel_01',
          doctorName: 'Dr. Arvind Patel',
          roomNumber: 'Room 4 (1st Floor)',
          counter: 'Counter 2',
          status: 'WAITING',
          priority: 'ROUTINE',
          positionInQueue: 2,
          estimatedWaitMinutes: 8,
          createdAt: new Date(Date.now() - 1200000).toISOString(),
        },
      ]);
    }

    // 10. Seed Medicine Inventory
    const medCount = await MedicineModel.countDocuments();
    if (medCount === 0) {
      console.log('[Seed] Seeding Medicine Inventory...');
      await MedicineModel.insertMany([
        {
          id: 'med_01',
          facilityId: 'fac_civil_01',
          medicineName: 'Paracetamol 500mg',
          genericName: 'Paracetamol',
          category: 'Analgesics / Antipyretics',
          batchNumber: 'PCM-2026-08',
          availableQuantity: 4500,
          minimumStockThreshold: 500,
          unit: 'Tablets',
          expiryDate: '2028-06-30',
          status: 'IN_STOCK',
          lastUpdated: new Date().toISOString(),
        },
        {
          id: 'med_02',
          facilityId: 'fac_civil_01',
          medicineName: 'Amlodipine Besylate 5mg',
          genericName: 'Amlodipine',
          category: 'Cardiovascular / Anti-Hypertensive',
          batchNumber: 'AML-2026-03',
          availableQuantity: 3200,
          minimumStockThreshold: 400,
          unit: 'Tablets',
          expiryDate: '2027-12-31',
          status: 'IN_STOCK',
          lastUpdated: new Date().toISOString(),
        },
        {
          id: 'med_03',
          facilityId: 'fac_civil_01',
          medicineName: 'Telmisartan 40mg',
          genericName: 'Telmisartan',
          category: 'Cardiovascular / ARB',
          batchNumber: 'TLM-2026-11',
          availableQuantity: 2800,
          minimumStockThreshold: 350,
          unit: 'Tablets',
          expiryDate: '2028-03-31',
          status: 'IN_STOCK',
          lastUpdated: new Date().toISOString(),
        },
        {
          id: 'med_04',
          facilityId: 'fac_civil_01',
          medicineName: 'Metformin Hydrochloride 500mg',
          genericName: 'Metformin',
          category: 'Endocrinology / Anti-Diabetic',
          batchNumber: 'MET-2026-04',
          availableQuantity: 5100,
          minimumStockThreshold: 600,
          unit: 'Tablets',
          expiryDate: '2028-01-31',
          status: 'IN_STOCK',
          lastUpdated: new Date().toISOString(),
        },
        {
          id: 'med_05',
          facilityId: 'fac_civil_01',
          medicineName: 'Cetirizine 10mg',
          genericName: 'Cetirizine',
          category: 'Antihistamine / Anti-Allergic',
          batchNumber: 'CTZ-2026-07',
          availableQuantity: 1800,
          minimumStockThreshold: 300,
          unit: 'Tablets',
          expiryDate: '2027-09-30',
          status: 'IN_STOCK',
          lastUpdated: new Date().toISOString(),
        },
      ]);
    }

    // 11. Seed Blood Center
    const bloodCount = await BloodCenterModel.countDocuments();
    if (bloodCount === 0) {
      console.log('[Seed] Seeding Blood Centers...');
      await BloodCenterModel.insertMany([
        {
          id: 'bc_civil_01',
          name: 'Civil Hospital Gandhinagar Regional Blood Bank',
          facilityId: 'fac_civil_01',
          district: 'Gandhinagar',
          contactNumber: '079-2322-1916 Ext 204',
          availableUnits: {
            'A+': 34,
            'A-': 8,
            'B+': 42,
            'B-': 6,
            'AB+': 18,
            'AB-': 4,
            'O+': 55,
            'O-': 12,
          },
          lastUpdated: new Date().toISOString(),
        },
      ]);
    }

    // 0. Seed Canonical Roles in RoleModel
    for (const r of SEED_ROLES) {
      await RoleModel.findOneAndUpdate(
        { code: r.code },
        { $set: r },
        { upsert: true, new: true }
      );
    }
    console.log(`[Seed] Standardized ${SEED_ROLES.length} System Roles in RoleModel.`);

    // 12. Seed Complete User Roster for All Roles & Facilities
    const CANONICAL_USERS = [
      // Super Admin (State Apex Grid)
      {
        id: 'usr_super_01',
        name: 'Dr. Jayesh Trivedi',
        username: 'superadmin',
        email: 'superadmin@gujarat.health.gov.in',
        phone: '9876500001',
        password: 'password123',
        role: 'SUPER_ADMIN',
        district: 'Gandhinagar',
        designation: 'State Principal Health Secretary',
        status: 'ACTIVE',
      },
      // District Admin (Gandhinagar)
      {
        id: 'usr_dist_01',
        name: 'Dr. Bhavik Mehta',
        username: 'districtadmin',
        email: 'bhavik.cdho@gandhinagar.health.gov.in',
        phone: '9876500006',
        password: 'password123',
        role: 'DISTRICT_ADMIN',
        district: 'Gandhinagar',
        designation: 'Chief District Health Officer (CDHO)',
        status: 'ACTIVE',
      },
      // District Admin (Ahmedabad)
      {
        id: 'usr_dist_ahd',
        name: 'Dr. Pradeep Solanki',
        username: 'ahd_admin',
        email: 'solanki.cdho@ahmedabad.health.gov.in',
        phone: '9876500016',
        password: 'password123',
        role: 'DISTRICT_ADMIN',
        district: 'Ahmedabad',
        designation: 'Chief District Health Officer (Ahmedabad)',
        status: 'ACTIVE',
      },
      // District Admin (Rajkot)
      {
        id: 'usr_dist_raj',
        name: 'Dr. Manish Dave',
        username: 'raj_admin',
        email: 'dave.cdho@rajkot.health.gov.in',
        phone: '9876500026',
        password: 'password123',
        role: 'DISTRICT_ADMIN',
        district: 'Rajkot',
        designation: 'Chief District Health Officer (Rajkot)',
        status: 'ACTIVE',
      },
      // Hospital Admin (Gandhinagar Civil)
      {
        id: 'usr_hosp_01',
        name: 'Dr. R. K. Patel',
        username: 'hospadmin',
        email: 'ms.civil@gandhinagar.health.gov.in',
        phone: '9876500007',
        password: 'password123',
        role: 'HOSPITAL_ADMIN',
        facilityId: 'fac_civil_01',
        facilityName: 'Gandhinagar Civil Hospital & Medical College',
        district: 'Gandhinagar',
        designation: 'Medical Superintendent',
        status: 'ACTIVE',
      },
      // Doctors on Duty
      {
        id: 'usr_doc_01',
        name: 'Dr. Arvind Patel',
        username: 'doctor',
        email: 'dr.arvind.patel@gujarat.gov.in',
        phone: '9876500002',
        password: 'password123',
        role: 'DOCTOR',
        facilityId: 'fac_civil_01',
        facilityName: 'Gandhinagar Civil Hospital & Medical College',
        district: 'Gandhinagar',
        specialty: 'General Medicine',
        department: 'General Medicine OPD',
        designation: 'Chief Medical Officer (OPD)',
        status: 'ACTIVE',
      },
      {
        id: 'usr_doc_cardio',
        name: 'Dr. K. P. Trivedi',
        username: 'dr_trivedi',
        email: 'dr.kptrivedi@unmehta.org',
        phone: '9876500012',
        password: 'password123',
        role: 'DOCTOR',
        facilityId: 'fac_un_mehta',
        facilityName: 'U. N. Mehta Institute of Cardiology & Research Centre',
        district: 'Ahmedabad',
        specialty: 'Cardiology',
        department: 'Cardiology & CCU',
        designation: 'Senior Interventional Cardiologist',
        status: 'ACTIVE',
      },
      {
        id: 'usr_doc_nephro',
        name: 'Dr. Pratik Dave',
        username: 'dr_dave',
        email: 'dr.dave@ikdrc.gov.in',
        phone: '9876500022',
        password: 'password123',
        role: 'DOCTOR',
        facilityId: 'fac_ikdrc',
        facilityName: 'Institute of Kidney Diseases and Research Centre (IKDRC)',
        district: 'Ahmedabad',
        specialty: 'Nephrology',
        department: 'Nephrology & Dialysis',
        designation: 'Chief Nephrologist',
        status: 'ACTIVE',
      },
      {
        id: 'usr_doc_onco',
        name: 'Dr. Meera Shah',
        username: 'dr_shah',
        email: 'dr.meera@gcri.org',
        phone: '9876500032',
        password: 'password123',
        role: 'DOCTOR',
        facilityId: 'fac_gcri',
        facilityName: 'The Gujarat Cancer & Research Institute (GCRI)',
        district: 'Ahmedabad',
        specialty: 'Oncology',
        department: 'Medical Oncology',
        designation: 'Senior Medical Oncologist',
        status: 'ACTIVE',
      },
      // Hospital Staff
      {
        id: 'usr_clerk_01',
        name: 'Govind Parmar',
        username: 'staff',
        email: 'govind.clerk@gujarat.gov.in',
        phone: '9876500004',
        password: 'password123',
        role: 'FACILITY_STAFF',
        staffSubType: 'REGISTRATION_CLERK',
        facilityId: 'fac_civil_01',
        facilityName: 'Gandhinagar Civil Hospital & Medical College',
        district: 'Gandhinagar',
        designation: 'Senior Registration Counter Officer',
        status: 'ACTIVE',
      },
      {
        id: 'usr_pharm_01',
        name: 'Vikram Joshi',
        username: 'pharmacist',
        email: 'vikram.pharm@gujarat.gov.in',
        phone: '9876500003',
        password: 'password123',
        role: 'FACILITY_STAFF',
        staffSubType: 'PHARMACIST',
        facilityId: 'fac_civil_01',
        facilityName: 'Gandhinagar Civil Hospital & Medical College',
        district: 'Gandhinagar',
        designation: 'Chief Pharmacist (Central Dispensary)',
        status: 'ACTIVE',
      },
      {
        id: 'usr_lab_01',
        name: 'Snehal Prajapati',
        username: 'labtech',
        email: 'snehal.lab@gujarat.gov.in',
        phone: '9876500005',
        password: 'password123',
        role: 'FACILITY_STAFF',
        staffSubType: 'LAB_TECHNICIAN',
        facilityId: 'fac_civil_01',
        facilityName: 'Gandhinagar Civil Hospital & Medical College',
        district: 'Gandhinagar',
        designation: 'Senior Pathology Lab Technician',
        status: 'ACTIVE',
      },
      // ASHA Worker
      {
        id: 'usr_asha_01',
        name: 'Anitaben Patel',
        username: 'asha',
        email: 'anita.asha@gujarat.gov.in',
        phone: '9876500009',
        password: 'password123',
        role: 'ASHA',
        facilityId: 'fac_civil_01',
        facilityName: 'Gandhinagar Civil Hospital & Medical College',
        district: 'Gandhinagar',
        designation: 'Community ASHA Coordinator',
        status: 'ACTIVE',
      },
    ];

    for (const u of CANONICAL_USERS) {
      const existing = await UserModel.findOne({ $or: [{ id: u.id }, { username: u.username }] });
      if (!existing) {
        await UserModel.create(u);
      } else {
        await UserModel.updateOne({ _id: existing._id }, { $set: u });
      }
    }
    console.log(`[Seed] Seeded / Upserted ${CANONICAL_USERS.length} Canonical Users across all Roles & Districts.`);

    // 13. Seed Appointments
    const aptCount = await AppointmentModel.countDocuments();
    if (aptCount === 0) {
      console.log('[Seed] Seeding sample OPD appointments...');
      const todayStr = new Date().toISOString().split('T')[0];
      await AppointmentModel.insertMany([
        {
          id: 'apt_sample_01',
          patientId: 'usr_pat_01',
          patientName: 'Rameshwar Sharma',
          patientPhone: '9876543210',
          patientAge: 48,
          patientGender: 'M',
          facilityId: 'fac_civil_01',
          facilityName: 'Gandhinagar Civil Hospital & Medical College',
          doctorId: 'doc_patel_01',
          doctorName: 'Dr. Arvind Patel',
          specialty: 'General Medicine',
          roomNumber: 'Room 4 (1st Floor)',
          date: todayStr,
          timeSlot: '10:30 AM',
          status: 'CONFIRMED',
          type: 'IN_PERSON',
          reasonForVisit: 'Hypertension follow-up and BP review',
          tokenNumber: 'OPD-28',
          createdAt: new Date().toISOString(),
        },
        {
          id: 'apt_sample_02',
          patientId: 'usr_pat_02',
          patientName: 'Kamlaben Vaghela',
          patientPhone: '9898012345',
          patientAge: 48,
          patientGender: 'F',
          facilityId: 'fac_civil_01',
          facilityName: 'Gandhinagar Civil Hospital & Medical College',
          doctorId: 'doc_patel_01',
          doctorName: 'Dr. Arvind Patel',
          specialty: 'General Medicine',
          roomNumber: 'Room 4 (1st Floor)',
          date: todayStr,
          timeSlot: '10:15 AM',
          status: 'CHECKED_IN',
          type: 'IN_PERSON',
          reasonForVisit: 'Severe body ache, mild fever for 3 days',
          tokenNumber: 'OPD-26',
          createdAt: new Date().toISOString(),
        },
        {
          id: 'apt_sample_03',
          patientId: 'usr_pat_03',
          patientName: 'Sanjaybhai Shah',
          patientPhone: '9825098765',
          patientAge: 38,
          patientGender: 'M',
          facilityId: 'fac_civil_01',
          facilityName: 'Gandhinagar Civil Hospital & Medical College',
          doctorId: 'doc_ortho_01',
          doctorName: 'Dr. Rajesh Varma',
          specialty: 'Orthopedics',
          roomNumber: 'Ortho Wing - Room 8',
          date: todayStr,
          timeSlot: '11:00 AM',
          status: 'SCHEDULED',
          type: 'IN_PERSON',
          reasonForVisit: 'Knee joint pain after minor twist',
          createdAt: new Date().toISOString(),
        },
      ]);
    }

    // 13. Seed Medical Stores with Precision Coordinates
    const storeCount = await MedicalStoreModel.countDocuments();
    if (storeCount === 0) {
      await MedicalStoreModel.insertMany([
        {
          id: 'store_pmbjp_01',
          name: 'Pradhan Mantri Bhartiya Janaushadhi Kendra (PMBJP) - Sector 21',
          type: 'JAN_AUSHADHI',
          isJanAushadhi: true,
          hasLiveApi: true,
          licenseNumber: 'GJ-GNR-PMBJP-0142',
          area: 'Sector 21 Market',
          fullAddress: 'Shop 14, Shopping Centre, Near SBI, Sector 21, Gandhinagar, Gujarat 382021',
          pincode: '382021',
          district: 'Gandhinagar',
          phone: '9825012345',
          whatsappPhone: '919825012345',
          timings: '8:00 AM - 10:00 PM (All 7 Days)',
          isOpenNow: true,
          rating: 4.9,
          reviewCount: 312,
          discountPercentage: 78,
          coordinates: { lat: 23.2268, lng: 72.6515 },
          location: { type: 'Point', coordinates: [72.6515, 23.2268] },
          stockCatalog: [
            { id: 'med_pcm_650', name: 'Tab. Paracetamol 650mg', genericName: 'Paracetamol IP 650mg', category: 'Antipyretic / Analgesic', dosage: '650 mg', status: 'IN_STOCK', quantityAvailable: 140, genericPrice: 12, brandPrice: 42, unit: 'Strip of 10 Tabs' },
            { id: 'med_panto_40', name: 'Tab. Pantoprazole 40mg', genericName: 'Pantoprazole Gastro-resistant IP 40mg', category: 'Antacid / PPI', dosage: '40 mg', status: 'IN_STOCK', quantityAvailable: 85, genericPrice: 16, brandPrice: 65, unit: 'Strip of 10 Tabs' },
            { id: 'med_met_500', name: 'Tab. Metformin 500mg SR', genericName: 'Metformin Hydrochloride Prolonged Release IP 500mg', category: 'Anti-Diabetic', dosage: '500 mg', status: 'IN_STOCK', quantityAvailable: 110, genericPrice: 14, brandPrice: 48, unit: 'Strip of 10 Tabs' },
            { id: 'med_amlo_5', name: 'Tab. Amlodipine 5mg', genericName: 'Amlodipine Besylate IP 5mg', category: 'Anti-Hypertensive', dosage: '5 mg', status: 'IN_STOCK', quantityAvailable: 95, genericPrice: 9, brandPrice: 38, unit: 'Strip of 10 Tabs' },
            { id: 'med_telmi_40', name: 'Tab. Telmisartan 40mg', genericName: 'Telmisartan IP 40mg', category: 'Anti-Hypertensive (ARB)', dosage: '40 mg', status: 'IN_STOCK', quantityAvailable: 70, genericPrice: 18, brandPrice: 75, unit: 'Strip of 10 Tabs' },
            { id: 'med_ator_10', name: 'Tab. Atorvastatin 10mg', genericName: 'Atorvastatin Calcium IP 10mg', category: 'Lipid Lowering / Statin', dosage: '10 mg', status: 'IN_STOCK', quantityAvailable: 60, genericPrice: 19, brandPrice: 85, unit: 'Strip of 10 Tabs' },
            { id: 'med_ors_pack', name: 'Electrolyte ORS Sachet 21.8g', genericName: 'Oral Rehydration Salts WHO Formula', category: 'Electrolyte / Rehydration', dosage: '21.8 g', status: 'IN_STOCK', quantityAvailable: 200, genericPrice: 5, brandPrice: 22, unit: '1 Sachet (for 1 Litre)' },
          ],
        },
        {
          id: 'store_pmbjp_02',
          name: 'PMBJP Jan Aushadhi Kendra - Civil Hospital Main Gate',
          type: 'JAN_AUSHADHI',
          isJanAushadhi: true,
          hasLiveApi: true,
          licenseNumber: 'GJ-GNR-PMBJP-0089',
          area: 'Civil Hospital Campus',
          fullAddress: 'Near OPD Gate No. 1, Gandhinagar District Civil Hospital, Sector 12, Gandhinagar 382012',
          pincode: '382012',
          district: 'Gandhinagar',
          phone: '9825023456',
          whatsappPhone: '919825023456',
          timings: 'Open 24x7 (Government Kendra)',
          isOpenNow: true,
          rating: 4.9,
          reviewCount: 540,
          discountPercentage: 80,
          coordinates: { lat: 23.2325, lng: 72.6582 },
          location: { type: 'Point', coordinates: [72.6582, 23.2325] },
          stockCatalog: [
            { id: 'med_pcm_650', name: 'Tab. Paracetamol 650mg', genericName: 'Paracetamol IP 650mg', category: 'Antipyretic / Analgesic', dosage: '650 mg', status: 'IN_STOCK', quantityAvailable: 240, genericPrice: 12, brandPrice: 42, unit: 'Strip of 10 Tabs' },
            { id: 'med_panto_40', name: 'Tab. Pantoprazole 40mg', genericName: 'Pantoprazole Gastro-resistant IP 40mg', category: 'Antacid / PPI', dosage: '40 mg', status: 'IN_STOCK', quantityAvailable: 150, genericPrice: 16, brandPrice: 65, unit: 'Strip of 10 Tabs' },
            { id: 'med_met_500', name: 'Tab. Metformin 500mg SR', genericName: 'Metformin Hydrochloride Prolonged Release IP 500mg', category: 'Anti-Diabetic', dosage: '500 mg', status: 'IN_STOCK', quantityAvailable: 180, genericPrice: 14, brandPrice: 48, unit: 'Strip of 10 Tabs' },
            { id: 'med_amlo_5', name: 'Tab. Amlodipine 5mg', genericName: 'Amlodipine Besylate IP 5mg', category: 'Anti-Hypertensive', dosage: '5 mg', status: 'IN_STOCK', quantityAvailable: 160, genericPrice: 9, brandPrice: 38, unit: 'Strip of 10 Tabs' },
            { id: 'med_amox_625', name: 'Tab. Amoxicillin + Clavulanic Acid 625mg', genericName: 'Amoxicillin and Potassium Clavulanate IP', category: 'Antibiotic', dosage: '625 mg', status: 'IN_STOCK', quantityAvailable: 85, genericPrice: 38, brandPrice: 125, unit: 'Strip of 6 Tabs' },
          ],
        },
        {
          id: 'store_pmbjp_03',
          name: 'PMBJP Jan Aushadhi Kendra - Sector 16 GIDC',
          type: 'JAN_AUSHADHI',
          isJanAushadhi: true,
          hasLiveApi: true,
          licenseNumber: 'GJ-GNR-PMBJP-0211',
          area: 'Sector 16 Market',
          fullAddress: 'Plot 418, Near Post Office, Sector 16, Gandhinagar, Gujarat 382016',
          pincode: '382016',
          district: 'Gandhinagar',
          phone: '9825034567',
          whatsappPhone: '919825034567',
          timings: '8:30 AM - 9:30 PM (Sun Closed)',
          isOpenNow: true,
          rating: 4.7,
          reviewCount: 188,
          discountPercentage: 75,
          coordinates: { lat: 23.2392, lng: 72.6644 },
          location: { type: 'Point', coordinates: [72.6644, 23.2392] },
          stockCatalog: [
            { id: 'med_pcm_650', name: 'Tab. Paracetamol 650mg', genericName: 'Paracetamol IP 650mg', category: 'Antipyretic / Analgesic', dosage: '650 mg', status: 'IN_STOCK', quantityAvailable: 100, genericPrice: 12, brandPrice: 42, unit: 'Strip of 10 Tabs' },
            { id: 'med_panto_40', name: 'Tab. Pantoprazole 40mg', genericName: 'Pantoprazole Gastro-resistant IP 40mg', category: 'Antacid / PPI', dosage: '40 mg', status: 'IN_STOCK', quantityAvailable: 70, genericPrice: 16, brandPrice: 65, unit: 'Strip of 10 Tabs' },
          ],
        },
        {
          id: 'store_pmbjp_04',
          name: 'Jan Aushadhi Kendra - Pethapur Community Health Complex',
          type: 'JAN_AUSHADHI',
          isJanAushadhi: true,
          hasLiveApi: true,
          licenseNumber: 'GJ-GNR-PMBJP-0304',
          area: 'Pethapur Main Bazaar',
          fullAddress: 'Opposite Pethapur PHC, Main Road, Pethapur, Gandhinagar 382610',
          pincode: '382610',
          district: 'Gandhinagar',
          phone: '9825045678',
          whatsappPhone: '919825045678',
          timings: '8:00 AM - 8:30 PM',
          isOpenNow: true,
          rating: 4.8,
          reviewCount: 145,
          discountPercentage: 76,
          coordinates: { lat: 23.2721, lng: 72.6688 },
          location: { type: 'Point', coordinates: [72.6688, 23.2721] },
          stockCatalog: [
            { id: 'med_pcm_650', name: 'Tab. Paracetamol 650mg', genericName: 'Paracetamol IP 650mg', category: 'Antipyretic / Analgesic', dosage: '650 mg', status: 'IN_STOCK', quantityAvailable: 120, genericPrice: 12, brandPrice: 42, unit: 'Strip of 10 Tabs' },
            { id: 'med_ors_pack', name: 'Electrolyte ORS Sachet 21.8g', genericName: 'Oral Rehydration Salts WHO Formula', category: 'Electrolyte / Rehydration', dosage: '21.8 g', status: 'IN_STOCK', quantityAvailable: 150, genericPrice: 5, brandPrice: 22, unit: '1 Sachet (for 1 Litre)' },
          ],
        },
        {
          id: 'store_hosp_01',
          name: 'Gandhinagar Civil Hospital Base OPD Pharmacy',
          type: 'HOSPITAL_PHARMACY',
          isJanAushadhi: false,
          hasLiveApi: true,
          licenseNumber: 'GOV-GNR-HOSP-PHARM-01',
          area: 'Civil Hospital Campus',
          fullAddress: 'Counter 2 & 3, Ground Floor OPD Wing, Gandhinagar Civil Hospital, Sector 12',
          pincode: '382012',
          district: 'Gandhinagar',
          phone: '07923221088',
          whatsappPhone: '917923221088',
          timings: 'Open 24 Hours (Emergency & OPD)',
          isOpenNow: true,
          rating: 4.6,
          reviewCount: 680,
          discountPercentage: 100,
          coordinates: { lat: 23.232, lng: 72.6575 },
          location: { type: 'Point', coordinates: [72.6575, 23.232] },
          stockCatalog: [
            { id: 'med_pcm_650', name: 'Tab. Paracetamol 650mg', genericName: 'Paracetamol IP 650mg', category: 'Antipyretic / Analgesic', dosage: '650 mg', status: 'IN_STOCK', quantityAvailable: 500, genericPrice: 0, brandPrice: 42, unit: 'Strip of 10 Tabs' },
            { id: 'med_panto_40', name: 'Tab. Pantoprazole 40mg', genericName: 'Pantoprazole Gastro-resistant IP 40mg', category: 'Antacid / PPI', dosage: '40 mg', status: 'IN_STOCK', quantityAvailable: 350, genericPrice: 0, brandPrice: 65, unit: 'Strip of 10 Tabs' },
            { id: 'med_met_500', name: 'Tab. Metformin 500mg SR', genericName: 'Metformin Hydrochloride Prolonged Release IP 500mg', category: 'Anti-Diabetic', dosage: '500 mg', status: 'IN_STOCK', quantityAvailable: 400, genericPrice: 0, brandPrice: 48, unit: 'Strip of 10 Tabs' },
          ],
        },
        {
          id: 'store_apollo_21',
          name: 'Apollo Pharmacy 24x7 - Sector 21',
          type: '24X7_EMERGENCY',
          isJanAushadhi: false,
          hasLiveApi: true,
          licenseNumber: 'GJ-24DL-APO-8819',
          area: 'Sector 21 Commercial Zone',
          fullAddress: 'Shop 4, Ground Floor, Ashoka Complex, Sector 21, Gandhinagar 382021',
          pincode: '382021',
          district: 'Gandhinagar',
          phone: '9825123450',
          whatsappPhone: '919825123450',
          timings: 'Open 24 Hours • All 365 Days',
          isOpenNow: true,
          rating: 4.7,
          reviewCount: 420,
          discountPercentage: 15,
          coordinates: { lat: 23.2275, lng: 72.6528 },
          location: { type: 'Point', coordinates: [72.6528, 23.2275] },
          stockCatalog: [
            { id: 'med_pcm_650', name: 'Tab. Paracetamol 650mg', genericName: 'Paracetamol IP 650mg', category: 'Antipyretic / Analgesic', dosage: '650 mg', status: 'IN_STOCK', quantityAvailable: 200, genericPrice: 35, brandPrice: 42, unit: 'Strip of 10 Tabs' },
          ],
        },
        {
          id: 'store_wellness_info',
          name: 'Wellness Forever 24x7 - Infocity',
          type: '24X7_EMERGENCY',
          isJanAushadhi: false,
          hasLiveApi: true,
          licenseNumber: 'GJ-24DL-WF-9901',
          area: 'Infocity Super Mall',
          fullAddress: 'GF-12, Super Mall 1, Infocity, Gandhinagar 382007',
          pincode: '382007',
          district: 'Gandhinagar',
          phone: '9825134561',
          whatsappPhone: '919825134561',
          timings: 'Open 24 Hours',
          isOpenNow: true,
          rating: 4.8,
          reviewCount: 390,
          discountPercentage: 12,
          coordinates: { lat: 23.1895, lng: 72.6288 },
          location: { type: 'Point', coordinates: [72.6288, 23.1895] },
          stockCatalog: [
            { id: 'med_pcm_650', name: 'Tab. Paracetamol 650mg', genericName: 'Paracetamol IP 650mg', category: 'Antipyretic / Analgesic', dosage: '650 mg', status: 'IN_STOCK', quantityAvailable: 180, genericPrice: 36, brandPrice: 42, unit: 'Strip of 10 Tabs' },
          ],
        },
        {
          id: 'store_kalol_01',
          name: 'PMBJP Jan Aushadhi Kendra - Kalol Highway',
          type: 'JAN_AUSHADHI',
          isJanAushadhi: true,
          hasLiveApi: true,
          licenseNumber: 'GJ-GNR-PMBJP-0419',
          area: 'Kalol Tower Road',
          fullAddress: 'Near Tower Chowk, Kalol, Gandhinagar District, Gujarat 382721',
          pincode: '382721',
          district: 'Gandhinagar',
          phone: '9825567890',
          whatsappPhone: '919825567890',
          timings: '8:00 AM - 10:00 PM',
          isOpenNow: true,
          rating: 4.8,
          reviewCount: 220,
          discountPercentage: 77,
          coordinates: { lat: 23.2435, lng: 72.4965 },
          location: { type: 'Point', coordinates: [72.4965, 23.2435] },
          stockCatalog: [
            { id: 'med_pcm_650', name: 'Tab. Paracetamol 650mg', genericName: 'Paracetamol IP 650mg', category: 'Antipyretic / Analgesic', dosage: '650 mg', status: 'IN_STOCK', quantityAvailable: 150, genericPrice: 12, brandPrice: 42, unit: 'Strip of 10 Tabs' },
          ],
        },
      ]);
    }

    console.log('[Seed] Database initialization verified with complete patient relations and medical stores.');
  } catch (err) {
    console.warn('[Seed] Note during database seeding:', err);
  }
}
