import { FacilityModel } from '../models/Facility';
import { DoctorModel } from '../models/Doctor';
import { UserModel } from '../models/User';
import { AppointmentModel, TokenModel } from '../models/Queue';

export const SEED_FACILITIES = [
  {
    id: 'fac_civil_01',
    name: 'Gandhinagar Civil Hospital & Medical College',
    type: 'DISTRICT_HOSPITAL',
    district: 'Gandhinagar',
    state: 'Gujarat',
    address: 'Sector 12, Gandhinagar, Gujarat 382012',
    pincode: '382012',
    contactNumber: '079-2322-1916',
    emergencyNumber: '108',
    coordinates: { lat: 23.2156, lng: 72.6369 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 15,
    totalBeds: 650,
    availableBeds: 84,
    icuBedsTotal: 60,
    icuBedsAvailable: 12,
    oxygenAvailable: true,
    bloodBankAvailable: true,
    ambulanceAvailable: true,
    specialties: [
      'General Medicine',
      'Cardiology',
      'Orthopedics',
      'Pediatrics',
      'Obstetrics & Gynecology',
      'General Surgery',
      'Dermatology',
      'Ophthalmology',
      'ENT',
      'Neurology',
    ],
    departments: [
      { id: 'dep_med', name: 'General Medicine OPD', code: 'GM-OPD', activeDoctors: 4, currentWaitMinutes: 12, opdOpen: true },
      { id: 'dep_cardio', name: 'Cardiology OPD', code: 'CARD-OPD', activeDoctors: 2, currentWaitMinutes: 20, opdOpen: true },
      { id: 'dep_ortho', name: 'Orthopedics OPD', code: 'ORTHO-OPD', activeDoctors: 3, currentWaitMinutes: 15, opdOpen: true },
      { id: 'dep_pedia', name: 'Pediatrics OPD', code: 'PED-OPD', activeDoctors: 2, currentWaitMinutes: 10, opdOpen: true },
      { id: 'dep_obg', name: 'Obstetrics & Gynecology OPD', code: 'OBG-OPD', activeDoctors: 3, currentWaitMinutes: 18, opdOpen: true },
      { id: 'dep_surg', name: 'General Surgery OPD', code: 'SURG-OPD', activeDoctors: 2, currentWaitMinutes: 25, opdOpen: true },
      { id: 'dep_derma', name: 'Dermatology OPD', code: 'DERM-OPD', activeDoctors: 2, currentWaitMinutes: 15, opdOpen: true },
      { id: 'dep_opht', name: 'Ophthalmology OPD', code: 'OPHT-OPD', activeDoctors: 2, currentWaitMinutes: 15, opdOpen: true },
    ],
  },
  {
    id: 'fac_pet_04',
    name: 'Pethapur Primary Health Centre',
    type: 'PHC',
    district: 'Gandhinagar',
    state: 'Gujarat',
    address: 'Near Gram Panchayat, Pethapur, Gandhinagar 382610',
    pincode: '382610',
    contactNumber: '079-2329-0123',
    emergencyNumber: '108',
    coordinates: { lat: 23.2842, lng: 72.6841 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: false,
    currentWaitTimeMinutes: 8,
    totalBeds: 12,
    availableBeds: 5,
    icuBedsTotal: 0,
    icuBedsAvailable: 0,
    oxygenAvailable: true,
    bloodBankAvailable: false,
    ambulanceAvailable: true,
    specialties: ['General Medicine', 'Maternal Health', 'Pediatrics'],
    departments: [
      { id: 'dep_med', name: 'General Medicine OPD', code: 'GM-OPD', activeDoctors: 2, currentWaitMinutes: 8, opdOpen: true },
      { id: 'dep_obg', name: 'Maternal Care', code: 'MAT-OPD', activeDoctors: 1, currentWaitMinutes: 10, opdOpen: true },
    ],
  },
  {
    id: 'fac_chc_02',
    name: 'Mansa Community Health Centre',
    type: 'CHC',
    district: 'Gandhinagar',
    state: 'Gujarat',
    address: 'Station Road, Mansa, Gujarat 382845',
    pincode: '382845',
    contactNumber: '02763-272022',
    emergencyNumber: '108',
    coordinates: { lat: 23.4287, lng: 72.6621 },
    isOpen: true,
    isVerified: true,
    emergencyAvailable: true,
    currentWaitTimeMinutes: 12,
    totalBeds: 45,
    availableBeds: 16,
    icuBedsTotal: 4,
    icuBedsAvailable: 2,
    oxygenAvailable: true,
    bloodBankAvailable: false,
    ambulanceAvailable: true,
    specialties: ['General Medicine', 'General Surgery', 'Obstetrics & Gynecology', 'Pediatrics'],
    departments: [
      { id: 'dep_med', name: 'General Medicine OPD', code: 'GM-OPD', activeDoctors: 2, currentWaitMinutes: 10, opdOpen: true },
      { id: 'dep_surg', name: 'General Surgery OPD', code: 'SURG-OPD', activeDoctors: 1, currentWaitMinutes: 15, opdOpen: true },
    ],
  },
];

export const SEED_DOCTORS = [
  {
    id: 'doc_patel_01',
    name: 'Dr. Arvind Patel',
    qualification: 'MBBS, MD (General Medicine)',
    specialty: 'General Medicine',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543201',
    email: 'dr.arvind.patel@gujarat.health.gov.in',
    opdSchedule: 'Mon-Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'Room 4 (1st Floor)',
    patientsToday: 14,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-28491',
  },
  {
    id: 'doc_mehta_02',
    name: 'Dr. Vikramaditya Mehta',
    qualification: 'MD (Gen Med), DNB',
    specialty: 'General Medicine',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543202',
    email: 'dr.v.mehta@gujarat.health.gov.in',
    opdSchedule: 'Mon, Wed, Fri: 9:00 AM - 2:00 PM',
    opdRoom: 'Room 6 (1st Floor)',
    patientsToday: 11,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-19342',
  },
  {
    id: 'doc_ananya_03',
    name: 'Dr. Ananya Patel',
    qualification: 'MBBS, DNB (Internal Medicine)',
    specialty: 'General Medicine',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543203',
    email: 'dr.ananya.patel@gujarat.health.gov.in',
    opdSchedule: 'Tue, Thu, Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'Room 2 (Ground Floor)',
    patientsToday: 8,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-34102',
  },
  {
    id: 'doc_cardio_01',
    name: 'Dr. K. P. Trivedi',
    qualification: 'MD, DM (Cardiology)',
    specialty: 'Cardiology',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543204',
    email: 'dr.kp.trivedi@gujarat.health.gov.in',
    opdSchedule: 'Mon-Fri: 10:00 AM - 2:00 PM',
    opdRoom: 'Cardio Wing - Room 12',
    patientsToday: 9,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-15201',
  },
  {
    id: 'doc_ortho_01',
    name: 'Dr. Rajesh Varma',
    qualification: 'MS (Orthopedics), M.Ch',
    specialty: 'Orthopedics',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543205',
    email: 'dr.rajesh.varma@gujarat.health.gov.in',
    opdSchedule: 'Mon, Tue, Thu, Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'Ortho Wing - Room 8',
    patientsToday: 12,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-22109',
  },
  {
    id: 'doc_pedia_01',
    name: 'Dr. Sangeeta Rao',
    qualification: 'MD (Pediatrics), DCH',
    specialty: 'Pediatrics',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543206',
    email: 'dr.sangeeta.rao@gujarat.health.gov.in',
    opdSchedule: 'Mon-Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'Child Health - Room 5',
    patientsToday: 15,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-31088',
  },
  {
    id: 'doc_obg_01',
    name: 'Dr. Neha Joshi',
    qualification: 'MS (Obstetrics & Gynecology)',
    specialty: 'Obstetrics & Gynecology',
    facilityId: 'fac_civil_01',
    facilityName: 'Gandhinagar Civil Hospital & Medical College',
    status: 'ON_DUTY',
    phone: '9876543207',
    email: 'dr.neha.joshi@gujarat.health.gov.in',
    opdSchedule: 'Mon-Sat: 9:00 AM - 2:00 PM',
    opdRoom: 'Maternity Wing - Room 10',
    patientsToday: 18,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-27411',
  },
  {
    id: 'doc_pet_01',
    name: 'Dr. Suresh Rawal',
    qualification: 'MBBS',
    specialty: 'General Medicine',
    facilityId: 'fac_pet_04',
    facilityName: 'Pethapur Primary Health Centre',
    status: 'ON_DUTY',
    phone: '9876543208',
    email: 'dr.suresh.rawal@gujarat.health.gov.in',
    opdSchedule: 'Mon-Sat: 9:00 AM - 1:00 PM',
    opdRoom: 'OPD Room 1',
    patientsToday: 7,
    teleconsultEnabled: true,
    district: 'Gandhinagar',
    registrationNumber: 'G-33120',
  },
];

export async function seedInitialDatabase(): Promise<void> {
  try {
    // 1. Seed Facilities
    const facCount = await FacilityModel.countDocuments();
    if (facCount === 0) {
      console.log('[Seed] Seeding initial healthcare facilities...');
      await FacilityModel.insertMany(SEED_FACILITIES);
    }

    // 2. Seed Doctors
    const docCount = await DoctorModel.countDocuments();
    if (docCount === 0) {
      console.log('[Seed] Seeding initial hospital doctors...');
      await DoctorModel.insertMany(SEED_DOCTORS);
    }

    // 3. Ensure Staff / Clerk Users
    const clerkUser = await UserModel.findOne({ role: 'FACILITY_STAFF', staffSubType: 'REGISTRATION_CLERK' });
    if (!clerkUser) {
      await UserModel.create({
        id: 'usr_clerk_01',
        name: 'Govind Parmar',
        email: 'govind.clerk@gujarat.gov.in',
        phone: '9876500004',
        password: 'password123',
        role: 'FACILITY_STAFF',
        staffSubType: 'REGISTRATION_CLERK',
        facilityId: 'fac_civil_01',
        facilityName: 'Gandhinagar Civil Hospital & Medical College',
        district: 'Gandhinagar',
        designation: 'Senior Registration Counter Officer',
      });
    }

    const doctorUser = await UserModel.findOne({ role: 'DOCTOR' });
    if (!doctorUser) {
      await UserModel.create({
        id: 'usr_doc_01',
        name: 'Dr. Arvind Patel',
        email: 'dr.arvind.patel@gujarat.gov.in',
        phone: '9876500002',
        password: 'password123',
        role: 'DOCTOR',
        facilityId: 'fac_civil_01',
        facilityName: 'Gandhinagar Civil Hospital & Medical College',
        district: 'Gandhinagar',
        specialty: 'General Medicine',
        designation: 'Chief Medical Officer (OPD)',
      });
    }

    // 4. Seed sample appointments if none exist
    const aptCount = await AppointmentModel.countDocuments();
    if (aptCount === 0) {
      console.log('[Seed] Seeding sample OPD appointments...');
      const todayStr = new Date().toISOString().split('T')[0];
      await AppointmentModel.insertMany([
        {
          id: 'apt_sample_01',
          patientId: 'usr_pat_01',
          patientName: 'Rameshbhai Patel',
          patientPhone: '9876543210',
          patientAge: 52,
          patientGender: 'M',
          facilityId: 'fac_civil_01',
          facilityName: 'Gandhinagar Civil Hospital & Medical College',
          doctorId: 'doc_patel_01',
          doctorName: 'Dr. Arvind Patel',
          specialty: 'General Medicine',
          roomNumber: 'Room 4 (1st Floor)',
          date: todayStr,
          timeSlot: '09:30 AM',
          status: 'CONFIRMED',
          type: 'IN_PERSON',
          reasonForVisit: 'Hypertension follow-up and routine BP check',
          createdAt: new Date().toISOString(),
        },
        {
          id: 'apt_sample_02',
          patientId: 'usr_pat_02',
          patientName: 'Kamlaben Vaghela',
          patientPhone: '9898012345',
          patientAge: 48,
          patientGender: 'F',
          facilityId: 'fac_civil_01',
          facilityName: 'Gandhinagar Civil Hospital & Medical College',
          doctorId: 'unassigned',
          doctorName: 'To be assigned at counter',
          specialty: 'General Medicine',
          date: todayStr,
          timeSlot: '10:15 AM',
          status: 'SCHEDULED',
          type: 'IN_PERSON',
          reasonForVisit: 'Severe body ache, mild fever for 3 days',
          createdAt: new Date().toISOString(),
        },
        {
          id: 'apt_sample_03',
          patientId: 'usr_pat_03',
          patientName: 'Sanjaybhai Shah',
          patientPhone: '9825098765',
          patientAge: 38,
          patientGender: 'M',
          facilityId: 'fac_civil_01',
          facilityName: 'Gandhinagar Civil Hospital & Medical College',
          doctorId: 'doc_ortho_01',
          doctorName: 'Dr. Rajesh Varma',
          specialty: 'Orthopedics',
          roomNumber: 'Ortho Wing - Room 8',
          date: todayStr,
          timeSlot: '11:00 AM',
          status: 'SCHEDULED',
          type: 'IN_PERSON',
          reasonForVisit: 'Knee joint pain after minor twist',
          createdAt: new Date().toISOString(),
        },
      ]);
    }

    console.log('[Seed] Database initialization verified.');
  } catch (err) {
    console.warn('[Seed] Note during database seeding:', err);
  }
}
